/** Portable presentation contract. No application APIs, authentication or database dependencies. */
export type Device='desktop'|'tablet'|'mobile';
export type Presentation={order:number;width:number;visible:boolean;spacing:'none'|'small'|'normal'|'large';align:'start'|'center'|'end'|'stretch';density:'normal'|'compact';surface:'transparent'|'base'|'panel'|'accent'|'white';container:'full'|'contained';border:'none'|'subtle'};
export type Responsive=Partial<Record<Device,Partial<Presentation>>>;
export type ElementBase={id:string;presentation:Presentation;responsive:Responsive};
export type Widget=ElementBase&{type:string;config:Record<string,unknown>};
export type Column=ElementBase&{widgets:Widget[]};
export type Section=ElementBase&{columns:Column[]};
export type Page={schema_version:1;page_id:string;sections:Section[]};
export type PermissionContext={role:string;permissions:readonly string[]};
export type MediaAsset={id:string;type:'image'|'video';source:string;filename:string;mime_type:string;width:number|null;height:number|null;alt:string;caption?:string|null;attribution?:string|null;rights_status?:'APPROVED'|'NEEDS_RIGHTS_REVIEW'|'UNKNOWN';provenance?:string;tags?:string[];created_at?:string;poster_id?:string};
export type MediaProvider={list:(query?:string,category?:string)=>Promise<MediaAsset[]>;get:(id:string)=>Promise<MediaAsset|null>;categories?:readonly string[];upload?:(file:File)=>Promise<MediaAsset>;archive?:(id:string)=>Promise<void>;validateSource:(asset:MediaAsset)=>boolean};
export type MediaConfig={asset:string|null;alt:string;decorative:boolean;fit:'cover'|'contain';x:number;y:number;ratio:'wide'|'square'|'portrait'|'natural';radius:'none'|'small'|'large';overlay:'none'|'light'|'medium'|'dark';tablet:Partial<Pick<MediaConfig,'asset'|'x'|'y'>>;mobile:Partial<Pick<MediaConfig,'asset'|'x'|'y'>>;autoplay:boolean;muted:boolean;loop:boolean;controls:boolean;poster:string|null};
export type ConfigField={key:string;label:string;kind:'text'|'number'|'choice'|'boolean';options?:readonly string[];min?:number;max?:number};
export type Definition={mediaKey?:string;type:string;label:string;category:string;icon:string;defaultConfig:Record<string,unknown>;validate:(config:Record<string,unknown>)=>void;fields:readonly ConfigField[];devices:readonly Device[];duplicate:boolean;context:readonly string[];allowed:(permission:PermissionContext)=>boolean;pages?:readonly string[]};
export type Registry=Record<string,Definition>;
export type Revision={id:number;number:number;created_at:string;actor_name:string;action:string};
export type RevisionAdapter={saveDraft:(page:Page,version:number)=>Promise<{version:number}>;publish:(page:Page,version:number)=>Promise<{version:number}>;revisions:()=>Promise<Revision[]>;restore:(id:number,version:number)=>Promise<{page:Page;version:number}>};
export const devices:Device[]=['desktop','tablet','mobile'];
export const presentation:Presentation={order:0,width:12,visible:true,spacing:'normal',align:'stretch',density:'normal',surface:'transparent',container:'full',border:'none'};
export const mediaDefaults:MediaConfig={asset:null,alt:'',decorative:false,fit:'cover',x:50,y:50,ratio:'wide',radius:'small',overlay:'none',tablet:{},mobile:{},autoplay:false,muted:true,loop:false,controls:true,poster:null};
export const id=()=>`pb-${globalThis.crypto.randomUUID()}`;
export function base(key=id(),order=0):ElementBase{return {id:key,presentation:{...presentation,order},responsive:{}};}
export function effective(element:ElementBase,device:Device):Presentation{return {...element.presentation,...element.responsive[device]};}
export const ordered=<T extends ElementBase>(items:T[],device:Device)=>[...items].sort((a,b)=>effective(a,device).order-effective(b,device).order);
export function object(value:unknown):asserts value is Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Expected an object.');}
export function keys(value:Record<string,unknown>,allowed:string[],required=allowed){if(Object.keys(value).some(k=>!allowed.includes(k))||required.some(k=>!(k in value)))throw Error('Unknown or missing configuration fields.');}
export function text(value:unknown,max=2000):asserts value is string{if(typeof value!=='string'||value.length>max||/[<>]/.test(value))throw Error('Use plain text within the allowed length.');}
function choice(value:unknown,values:readonly unknown[]){if(!values.includes(value))throw Error('Unsupported presentation option.');}
function number(value:unknown,min:number,max:number,integer=false){if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max||(integer&&!Number.isInteger(value)))throw Error('Invalid numeric setting.');}
export function validateMedia(c:Record<string,unknown>){keys(c,Object.keys(mediaDefaults));for(const k of ['asset','poster'])if(c[k]!==null&&(typeof c[k]!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9:_-]{0,159}$/.test(c[k] as string)))throw Error('Invalid media reference.');text(c.alt,500);choice(c.fit,['cover','contain']);choice(c.ratio,['wide','square','portrait','natural']);choice(c.radius,['none','small','large']);choice(c.overlay,['none','light','medium','dark']);number(c.x,0,100);number(c.y,0,100);for(const k of ['decorative','autoplay','muted','loop','controls'])choice(c[k],[true,false]);if(c.autoplay&&!c.muted)throw Error('Autoplay requires muted video.');if(!c.controls)throw Error('Video controls must remain available.');for(const d of ['tablet','mobile']){object(c[d]);keys(c[d],['asset','x','y'],[]);for(const [k,v] of Object.entries(c[d])){if(k==='asset'){if(v!==null&&(typeof v!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9:_-]{0,159}$/.test(v)))throw Error('Invalid responsive media reference.');}else number(v,0,100);}}}
export function mediaFor(config:MediaConfig,device:Device):MediaConfig{return {...config,...(device==='desktop'?{}:config[device])};}
function validatePresentation(v:unknown,partial=false){object(v);keys(v,Object.keys(presentation),partial?[]:Object.keys(presentation));for(const [k,x] of Object.entries(v)){switch(k){case 'order':number(x,0,1000,true);break;case 'width':number(x,1,12,true);break;case 'visible':choice(x,[true,false]);break;case 'spacing':choice(x,['none','small','normal','large']);break;case 'align':choice(x,['start','center','end','stretch']);break;case 'density':choice(x,['normal','compact']);break;case 'surface':choice(x,['transparent','base','panel','accent','white']);break;case 'container':choice(x,['full','contained']);break;case 'border':choice(x,['none','subtle']);break;}}}
export function validatePage(value:unknown,registry:Registry,pageId?:string):Page{
 object(value);keys(value,['schema_version','page_id','sections']);if(value.schema_version!==1)throw Error('Unsupported page schema version.');text(value.page_id,80);if(!/^[a-z][a-z0-9-]{0,79}$/.test(value.page_id)||pageId&&value.page_id!==pageId)throw Error('Invalid page context.');
 const seen=new Set<string>();let count=0;
 function common(v:unknown,extra:string[]){object(v);keys(v,['id','presentation','responsive',...extra]);if(typeof v.id!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,79}$/.test(v.id)||seen.has(v.id))throw Error('Element IDs must be unique and stable.');seen.add(v.id);if(++count>250)throw Error('Page is too large.');validatePresentation(v.presentation);object(v.responsive);keys(v.responsive,devices,[]);Object.values(v.responsive).forEach(p=>validatePresentation(p,true));return v;}
 if(!Array.isArray(value.sections)||value.sections.length>30)throw Error('Invalid sections.');
 for(const raw of value.sections){const s=common(raw,['columns']);if(!Array.isArray(s.columns)||s.columns.length<1||s.columns.length>12)throw Error('Sections need 1–12 columns.');for(const rawC of s.columns){const c=common(rawC,['widgets']);if(!Array.isArray(c.widgets)||c.widgets.length>50)throw Error('Invalid widgets.');for(const rawW of c.widgets){const w=common(rawW,['type','config']);if(typeof w.type!=='string'||!Object.prototype.hasOwnProperty.call(registry,w.type))throw Error('Unknown widget.');const def=registry[w.type];if(def.pages&&!def.pages.includes(value.page_id as string))throw Error('Widget is not valid for this page.');object(w.config);def.validate(w.config);}}}
 const widgets=(value.sections as Section[]).flatMap(s=>s.columns.flatMap(c=>c.widgets));for(const [type,def] of Object.entries(registry))if(!def.duplicate&&widgets.filter(w=>w.type===type).length>1)throw Error('This business widget cannot be duplicated.');
 return structuredClone(value) as Page;
}
export function exportPage(page:Page,registry:Registry){const valid=validatePage(page,registry);const canonical=(x:unknown):unknown=>Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,canonical(v)])):x;return JSON.stringify(canonical(valid),null,2);}
export function importPage(raw:string,registry:Registry,pageId?:string){if(raw.length>100000)throw Error('Layout JSON exceeds 100 KB.');return validatePage(JSON.parse(raw),registry,pageId);}
export function migratePage(raw:unknown,migrations:Record<number,(v:unknown)=>unknown>={}){object(raw);const version=raw.schema_version;if(version===1)return raw;if(typeof version==='number'&&migrations[version])return migrations[version](raw);throw Error('No migration for this schema version.');}
export type EditHistory={past:Page[];present:Page;future:Page[]};
export const editHistory=(page:Page):EditHistory=>({past:[],present:structuredClone(page),future:[]});
export function commit(history:EditHistory,page:Page):EditHistory{return {past:[...history.past,history.present].slice(-50),present:structuredClone(page),future:[]};}
export function undo(h:EditHistory):EditHistory{return h.past.length?{past:h.past.slice(0,-1),present:h.past[h.past.length-1],future:[h.present,...h.future]}:h;}
export function redo(h:EditHistory):EditHistory{return h.future.length?{past:[...h.past,h.present],present:h.future[0],future:h.future.slice(1)}:h;}
export function locate(page:Page,key:string){for(const s of page.sections){if(s.id===key)return {element:s,kind:'section' as const,parent:page.sections};for(const c of s.columns){if(c.id===key)return {element:c,kind:'column' as const,parent:s.columns};for(const w of c.widgets)if(w.id===key)return {element:w,kind:'widget' as const,parent:c.widgets};}}return null;}
export function moveElement(page:Page,key:string,target:string,device:Device):Page{const next=structuredClone(page),from=locate(next,key),to=locate(next,target);if(!from||!to||key===target)return next;if(from.kind==='widget'&&to.kind==='column'){const parent=from.parent as Widget[];parent.splice(parent.findIndex(x=>x.id===key),1);const column=to.element as Column;column.widgets=ordered(column.widgets,device);column.widgets.push(from.element as Widget);column.widgets.forEach((x,i)=>x.responsive[device]={...x.responsive[device],order:i});return next;}if(from.kind!==to.kind)return next;const a=from.parent as ElementBase[],b=to.parent as ElementBase[];if(from.kind!=='widget'&&a!==b)return next;const sorted=ordered(b,device);const index=sorted.findIndex(x=>x.id===target);a.splice(a.findIndex(x=>x.id===key),1);const remaining=sorted.filter(x=>x.id!==key);remaining.splice(index,0,from.element);b.push(from.element);remaining.forEach((x,i)=>x.responsive[device]={...x.responsive[device],order:i});return next;}
export function canRender(def:Definition,permissions:PermissionContext,context:Record<string,unknown>){return def.allowed(permissions)&&def.context.every(key=>context[key]!==undefined&&context[key]!==null);}
const field=(key:string,label:string,kind:ConfigField['kind'],options?:string[]):ConfigField=>({key,label,kind,options});
const generic=(type:string,label:string,defaults:Record<string,unknown>,fields:ConfigField[],validate:Definition['validate']):Definition=>({type,label,category:'General',icon:type,defaultConfig:defaults,fields,validate,devices,duplicate:true,context:[],allowed:()=>true});
export const coreRegistry:Registry={
 heading:generic('heading','Heading',{text:'Heading',level:'h2'},[field('text','Heading text','text'),field('level','Heading level','choice',['h2','h3','h4'])],c=>{keys(c,['text','level']);text(c.text,200);choice(c.level,['h2','h3','h4']);}),
 text:generic('text','Text',{text:'Add helpful context.'},[field('text','Text','text')],c=>{keys(c,['text']);text(c.text);}),
 divider:generic('divider','Divider',{},[],c=>keys(c,[])),
 spacer:generic('spacer','Spacer',{size:'normal'},[field('size','Space','choice',['small','normal','large'])],c=>{keys(c,['size']);choice(c.size,['small','normal','large']);}),
 metric:generic('metric','Metric',{label:'Metric',value:'—'},[field('label','Label','text'),field('value','Display value','text')],c=>{keys(c,['label','value']);text(c.label,120);text(c.value,60);}),
 list:generic('list','Generic List',{text:'First item\nSecond item'},[field('text','Items · one per line','text')],c=>{keys(c,['text']);text(c.text);}),
 media:generic('media','Image / Media',structuredClone(mediaDefaults) as unknown as Record<string,unknown>,[],validateMedia),
};
