'use client';
import './editor.css';
import {useEffect,useRef,useState,type ReactNode,type PointerEvent} from 'react';
import {base,commit,devices,editHistory,effective,exportPage,id,importPage,locate,mediaDefaults,mediaFor,moveElement,ordered,redo,undo,validatePage,type Column,type Device,type ElementBase,type MediaAsset,type MediaConfig,type Page,type Presentation,type Revision,type RevisionAdapter,type Section,type Widget} from './core';
import {elementProps,PageRenderer,WidgetView,type RenderContext,type RuntimeRegistry} from './runtime';
export type EditorProps={initial:Page;defaults:Page;registry:RuntimeRegistry;context:RenderContext;version?:number;adapter?:Pick<RevisionAdapter,'saveDraft'>&Partial<Omit<RevisionAdapter,'saveDraft'>>;renderCanvas?:(node:ReactNode,device:Device,page:Page,preview:boolean)=>ReactNode;surfaceLabels?:Record<string,string>;exit:()=>void};
export default function PageEditor({initial,defaults,registry,context,version=0,adapter,renderCanvas,surfaceLabels,exit}:EditorProps){
 const [history,setHistory]=useState(()=>editHistory(validatePage(initial,registry))),[device,setDevice]=useState<Device>(context.device),[selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState('Structure'),[preview,setPreview]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[currentVersion,setVersion]=useState(version),[exports,setExports]=useState(false),[input,setInput]=useState(''),[revisions,setRevisions]=useState<Revision[]|null>(null),[target,setTarget]=useState<string|null>(null),[savedPage,setSavedPage]=useState(()=>JSON.stringify(initial));
 const root=useRef<HTMLDivElement>(null),heading=useRef<HTMLHeadingElement>(null),output=useRef<HTMLTextAreaElement>(null),drag=useRef<{key:string;x:number;y:number;target:string|null;active:boolean;pointer:number;frame:number;clientY:number}|null>(null);
 const dirty=JSON.stringify(history.present)!==savedPage;
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const page=history.present,found=selected?locate(page,selected):null,activeContext={...context,device};
 useEffect(()=>{heading.current?.focus();return()=>{if(drag.current)cancelAnimationFrame(drag.current.frame);};},[]);
 function change(next:Page,notice='Draft changed. Save Draft to keep it on the server.'){try{validatePage(next,registry,initial.page_id);setHistory(h=>commit(h,next));setMessage(notice);setError('');}catch(e){setError((e as Error).message);}}
 function modify(fn:(p:Page)=>void){const next=structuredClone(page);fn(next);change(next);}
 function select(key:string){setSelected(key);setTab('Settings');}
 function settings(values:Partial<Presentation>){if(!selected)return;modify(p=>{const e=locate(p,selected)?.element;if(e)e.responsive[device]={...e.responsive[device],...values};});}
 function config(values:Record<string,unknown>){if(!selected)return;modify(p=>{const e=locate(p,selected);if(e?.kind==='widget')(e.element as Widget).config={...(e.element as Widget).config,...values};});}
 function addSection(){const section:Section={...base(),columns:[{...base(),widgets:[]}]};modify(p=>{section.presentation.order=p.sections.length;p.sections.push(section);});select(section.id);}
 function addColumn(){if(!found)return;const section=found.kind==='section'?found.element as Section:page.sections.find(s=>s.columns.some(c=>c.id===selected||c.widgets.some(w=>w.id===selected)));if(!section)return;modify(p=>{const s=locate(p,section.id)?.element as Section;s.columns.push({...base(),widgets:[]});const width=Math.max(1,Math.floor(12/s.columns.length));s.columns.forEach((c,i)=>c.responsive[device]={...c.responsive[device],width,order:i});});}
 function addWidget(type:string){const column=found?.kind==='column'?found.element as Column:found?.kind==='widget'?page.sections.flatMap(s=>s.columns).find(c=>c.widgets.some(w=>w.id===selected)):page.sections.flatMap(s=>s.columns)[0];if(!column){setError('Add a section and choose a column first.');return;}const def=registry[type];const widget:Widget={...base(),type,config:structuredClone(def.defaultConfig)};modify(p=>{const c=locate(p,column.id)?.element as Column;widget.presentation.order=c.widgets.length;c.widgets.push(widget);});select(widget.id);}
 function remove(){if(!selected)return;modify(p=>{const f=locate(p,selected);if(f){const list=f.parent as ElementBase[];list.splice(list.findIndex(e=>e.id===selected),1);}});setSelected(null);setTab('Structure');}
 function duplicate(){if(!found)return;const copy=structuredClone(found.element);const renew=(e:ElementBase)=>{e.id=id();if('columns' in e)(e as Section).columns.forEach(renew);if('widgets' in e)(e as Column).widgets.forEach(renew);};renew(copy);modify(p=>{const f=locate(p,found.element.id)!;(f.parent as ElementBase[]).push(copy);copy.responsive[device]={...copy.responsive[device],order:Math.max(...f.parent.map(e=>effective(e,device).order))+1};});}
 function move(delta:number){if(!found)return;const list=ordered(found.parent as ElementBase[],device),at=list.findIndex(e=>e.id===selected),to=list[at+delta];if(to)change(moveElement(page,found.element.id,to.id,device),'Element moved.');}
 function finish(cancel=false){const d=drag.current;if(!d)return;cancelAnimationFrame(d.frame);if(d.active&&d.target&&!cancel)change(moveElement(page,d.key,d.target,device),'Element moved.');drag.current=null;setTarget(null);}
 function start(e:PointerEvent<HTMLButtonElement>,key:string){if(e.button!==0||drag.current)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={key,x:e.clientX,y:e.clientY,target:null,active:false,pointer:e.pointerId,frame:0,clientY:viewportY(e)};const tick=()=>{const d=drag.current;if(!d)return;if(d.active){const dy=d.clientY<90?-10:d.clientY>innerHeight-90?10:0;if(dy)scrollBy(0,dy);}d.frame=requestAnimationFrame(tick);};drag.current.frame=requestAnimationFrame(tick);}
 function dragging(e:PointerEvent<HTMLButtonElement>){const d=drag.current;if(!d)return;d.clientY=viewportY(e);if(!d.active&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<8)return;d.active=true;const source=locate(page,d.key);let hit=e.currentTarget.ownerDocument.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-pb-key]');while(hit){const candidate=locate(page,hit.dataset.pbKey||'');if(candidate&&(candidate.kind===source?.kind||source?.kind==='widget'&&candidate.kind==='column'))break;hit=hit.parentElement?.closest<HTMLElement>('[data-pb-key]');}const key=hit?.dataset.pbKey;d.target=key&&locate(page,key)?key:null;setTarget(d.target);}
 async function persist(action:'draft'|'publish'){if(!adapter)return;setBusy(true);setError('');try{const result=await(action==='draft'?adapter.saveDraft(page,currentVersion):adapter.publish!(page,currentVersion));setVersion(result.version);setSavedPage(JSON.stringify(page));setMessage(action==='draft'?'Draft saved. Published page unchanged.':'Page published.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const bar=(e:ElementBase,title:string)=><div className="pb-node-bar"><button type="button" className="pb-handle" aria-label={`Drag ${title}`} onPointerDown={p=>start(p,e.id)} onPointerMove={dragging} onPointerUp={()=>finish()} onPointerCancel={()=>finish(true)} onLostPointerCapture={()=>finish(true)}>⠿</button><button type="button" aria-pressed={selected===e.id} onClick={()=>select(e.id)}>{title}{!effective(e,device).visible?' · Hidden':''}</button></div>;
 const node=(e:ElementBase)=>({'data-pb-key':e.id,'data-selected':selected===e.id,'data-target':target===e.id,className:elementProps(e,device).className+' pb-editor-node',style:elementProps(e,device).style});
 const sectionTitle=(s:Section,i:number)=>s.columns[0]?.widgets[0]?registry[s.columns[0].widgets[0].type].label:`Section ${i+1}`;
 const tree=<ul className="pb-tree">{ordered(page.sections,device).map((s,i)=><li key={s.id}><button type="button" onClick={()=>select(s.id)}>{sectionTitle(s,i)}{!effective(s,device).visible?' · Hidden':''}</button><ul>{ordered(s.columns,device).map((c,j)=><li key={c.id}><button type="button" onClick={()=>select(c.id)}>Column {j+1}</button><ul>{ordered(c.widgets,device).map(w=><li key={w.id}><button type="button" onClick={()=>select(w.id)}>{registry[w.type].label}{!effective(w,device).visible?' · Hidden':''}</button></li>)}</ul></li>)}</ul></li>)}</ul>;
 const p=found?effective(found.element,device):null;
 const selectedWidget=found?.kind==='widget'?found.element as Widget:null;
 const mediaKey=selectedWidget?registry[selectedWidget.type].mediaKey:undefined;
 const hasMedia=selectedWidget&&(selectedWidget.type==='media'||mediaKey!==undefined);
 const mediaConfig=hasMedia?(mediaKey?(selectedWidget!.config[mediaKey] as MediaConfig|undefined)||structuredClone(mediaDefaults):selectedWidget!.config as unknown as MediaConfig):mediaDefaults;
 function updateMedia(values:Record<string,unknown>){config(mediaKey?{[mediaKey]:{...mediaConfig,...values}}:values);}
 function resetMedia(){if(mediaKey&&selectedWidget)modify(p=>{delete (locate(p,selectedWidget.id)!.element as Widget).config[mediaKey];});else config(structuredClone(mediaDefaults) as unknown as Record<string,unknown>);}

 const duplicateSafe=found&&('type'in found.element?registry[(found.element as Widget).type].duplicate:'columns'in found.element?(found.element as Section).columns.every(c=>c.widgets.every(w=>registry[w.type].duplicate)):(found.element as Column).widgets.every(w=>registry[w.type].duplicate));
 function moveColumn(delta:number){if(found?.kind!=='widget')return;const columns=page.sections.flatMap(s=>ordered(s.columns,device));const at=columns.findIndex(c=>c.widgets.some(w=>w.id===selected));const to=columns[at+delta];if(to)change(moveElement(page,found.element.id,to.id,device),'Widget moved to adjacent column.');}

 return <div ref={root} className="pb-editor" onKeyDown={e=>{if(e.key==='Escape'&&drag.current){e.preventDefault();finish(true);setMessage('Drag cancelled.');}}}><header className="pb-editor-top"><small>6DS PAGE BUILDER · PRESENTATION ONLY</small><h2 tabIndex={-1} ref={heading}>Edit Page · {initial.page_id}</h2><p className="pb-preview-note">Live content is read-only while editing. Layouts never grant business permissions.</p><div className="pb-editor-actions"><div role="group" aria-label="Preview device">{devices.map(d=><button type="button" key={d} aria-pressed={d===device} onClick={()=>{finish(true);setDevice(d);}}>{d[0].toUpperCase()+d.slice(1)}</button>)}</div><button type="button" disabled={!history.past.length} onClick={()=>setHistory(undo)}>Undo</button><button type="button" disabled={!history.future.length} onClick={()=>setHistory(redo)}>Redo</button><button type="button" aria-pressed={preview} onClick={()=>setPreview(!preview)}>Preview</button>{adapter&&<><button type="button" disabled={busy} onClick={()=>persist('draft')}>Save Draft</button>{adapter.publish&&<button type="button" disabled={busy} onClick={()=>persist('publish')}>Publish</button>}{adapter.revisions&&<button type="button" disabled={busy} onClick={async()=>{try{setRevisions(await adapter.revisions!());}catch(e){setError((e as Error).message);}}}>Revisions</button>}</>}<button type="button" onClick={()=>setExports(!exports)}>Export / Import</button><button type="button" onClick={()=>{if(!dirty||window.confirm('Discard unsaved draft changes and exit?'))exit();}}>Exit</button></div></header>
 <p role="status" className="pb-editor-alert">{message}</p>{error&&<p role="alert" className="pb-editor-alert">{error}</p>}
 {exports&&<section className="pb-export"><h3>Layout JSON</h3><div className="pb-editor-actions"><button type="button" onClick={()=>{const url=URL.createObjectURL(new Blob([exportPage(page,registry)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=page.page_id+'-v1.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download JSON</button><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(exportPage(page,registry));setMessage('JSON copied.');}catch{output.current?.focus();output.current?.select();setMessage('Copy the selected JSON below.');}}}>Copy JSON</button></div><label>Complete layout JSON<textarea aria-label="Complete layout JSON" ref={output} readOnly rows={8} value={exportPage(page,registry)}/></label><label>Import layout JSON<textarea aria-label="Import layout JSON" rows={4} value={input} maxLength={100000} onChange={e=>setInput(e.target.value)}/></label><button type="button" onClick={()=>{try{change(importPage(input,registry,initial.page_id),'Layout imported into draft.');setSelected(null);}catch(e){setError((e as Error).message);}}}>Import into draft</button></section>}
 {revisions&&<section className="pb-revisions"><h3>Published revisions</h3>{revisions.length?revisions.map(r=><p key={r.id}>Revision {r.number} · {new Date(r.created_at).toLocaleString()} · {r.actor_name} · {r.action} <button type="button" disabled={busy} onClick={async()=>{setBusy(true);try{const result=await adapter!.restore!(r.id,currentVersion);setVersion(result.version);setHistory(editHistory(validatePage(result.page,registry)));setRevisions(await adapter!.revisions!());setMessage('Restored as a new published revision.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Restore revision {r.number}</button></p>):<p>No published revisions.</p>}<button type="button" onClick={()=>setRevisions(null)}>Close revisions</button></section>}
 <div className="pb-editor-workspace">{!preview&&<aside className="pb-editor-panel" aria-label="Page builder controls"><div role="tablist" aria-label="Builder panels" onKeyDown={e=>{const tabs=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('[role=tab]')),at=tabs.indexOf(e.target as HTMLButtonElement);const next=e.key==='ArrowRight'?(at+1)%tabs.length:e.key==='ArrowLeft'?(at+tabs.length-1)%tabs.length:e.key==='Home'?0:e.key==='End'?tabs.length-1:-1;if(next>=0){e.preventDefault();tabs[next].focus();tabs[next].click();}}}>{['Widgets','Structure','Settings','Media'].map(t=><button type="button" role="tab" tabIndex={tab===t?0:-1} aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Structure'&&<><button type="button" onClick={addSection}>Add section</button>{tree}</>}
 {tab==='Widgets'&&<><p>Choose a column, then add a widget.</p>{Object.values(registry).filter(d=>!d.pages||d.pages.includes(page.page_id)).filter(d=>d.allowed(context.permissions)).map(d=><button type="button" key={d.type} onClick={()=>addWidget(d.type)}>{d.label}</button>)}</>}
 {tab==='Settings'&&(!found?<p>Select an element on the canvas or in Structure.</p>:<><h3>{found.kind==='widget'?registry[(found.element as Widget).type].label:found.kind==='section'?'Section':'Column'}</h3><p className="pb-preview-note">Presentation settings apply to {device}. Adding, removing or moving between columns changes the shared structure.</p><div className="pb-editor-actions"><button type="button" onClick={()=>move(-1)}>{found.kind==='column'?'Move Left':'Move Up'}</button><button type="button" onClick={()=>move(1)}>{found.kind==='column'?'Move Right':'Move Down'}</button><button type="button" disabled={!duplicateSafe} onClick={duplicate}>Duplicate</button><button type="button" onClick={remove}>Remove</button>{found.kind!=='widget'&&<button type="button" onClick={addColumn}>Add column</button>}</div><label>Visible on {device}<select aria-label="Visibility" value={String(p!.visible)} onChange={e=>settings({visible:e.target.value==='true'})}><option value="true">Visible</option><option value="false">Hidden</option></select></label>{(['width','spacing','align','density','surface','container','border'] as const).map(k=><label key={k}>{k}<select aria-label={k} value={String(p![k])} onChange={e=>settings({[k]:k==='width'?Number(e.target.value):e.target.value})}>{(k==='width'?Array.from({length:12},(_,i)=>i+1):k==='spacing'?['none','small','normal','large']:k==='align'?['start','center','end','stretch']:k==='density'?['normal','compact']:k==='surface'?['transparent','base','panel','accent','white']:k==='container'?['full','contained']:['none','subtle']).map(v=><option key={v} value={v}>{k==='surface'?surfaceLabels?.[String(v)]||v:v}</option>)}</select></label>)}<button type="button" onClick={()=>modify(n=>{delete locate(n,found.element.id)!.element.responsive[device];})}>Clear device overrides</button>
 {found.kind==='widget'&&<><div className="pb-editor-actions"><button type="button" onClick={()=>moveColumn(-1)}>Move Left</button><button type="button" onClick={()=>moveColumn(1)}>Move Right</button></div><label>Move to column<select aria-label="Move to column" value="" onChange={e=>{if(e.target.value)change(moveElement(page,found.element.id,e.target.value,device));}}><option value="">Choose destination</option>{page.sections.flatMap((s,i)=>s.columns.map((c,j)=><option key={c.id} value={c.id}>Section {i+1}, column {j+1}</option>))}</select></label>{registry[(found.element as Widget).type].fields.map(f=><label key={f.key}>{f.label}{f.kind==='choice'?<select aria-label={f.label} value={String((found.element as Widget).config[f.key])} onChange={e=>config({[f.key]:e.target.value})}>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:f.kind==='boolean'?<select aria-label={f.label} value={String((found.element as Widget).config[f.key])} onChange={e=>config({[f.key]:e.target.value==='true'})}><option value="false">Off</option><option value="true">On</option></select>:f.kind==='number'?<input aria-label={f.label} type="number" min={f.min} max={f.max} value={typeof (found.element as Widget).config[f.key]==='number'?Number((found.element as Widget).config[f.key]):''} onChange={e=>config({[f.key]:e.target.valueAsNumber})}/>:f.key==='href'?<LinkField label={f.label} value={String((found.element as Widget).config[f.key]??'')} save={value=>{if(value)config({[f.key]:value});else modify(p=>{delete (locate(p,found.element.id)!.element as Widget).config[f.key];});}}/>:<textarea aria-label={f.label} rows={3} maxLength={2000} value={String((found.element as Widget).config[f.key]??'')} onChange={e=>config({[f.key]:e.target.value})}/>}</label>)}{hasMedia&&<button type="button" onClick={()=>setTab('Media')}>Change Image</button>}</>}
 <button type="button" onClick={()=>{change(structuredClone(defaults),'Source-controlled default loaded into draft.');setSelected(null);}}>Reset page to default</button></>)}
 {tab==='Media'&&<MediaControls key={selectedWidget?.id||'library'} config={mediaConfig} change={updateMedia} context={activeContext} reset={resetMedia} selectable={!!hasMedia}/>}

 </aside>}<div className={`pb-editor-canvas pb-preview-${device}`}>
 {(renderCanvas||((node:ReactNode)=>node))(preview?<div ref={n=>{if(n)n.inert=true;}}><PageRenderer page={page} registry={registry} context={activeContext}/></div>:<div className="pb-page">{ordered(page.sections,device).map((s,i)=><section key={s.id} {...node(s)}>{bar(s,sectionTitle(s,i))}<div className="pb-columns">{ordered(s.columns,device).map((c,j)=><div key={c.id} {...node(c)}>{bar(c,`Column ${j+1}`)}<div className="pb-widgets">{ordered(c.widgets,device).map(w=><article key={w.id} {...node(w)}>{bar(w,registry[w.type].label)}<div className="pb-readonly" ref={n=>{if(n)n.inert=true;}}><WidgetView widget={w} registry={registry} context={activeContext}/></div></article>)}</div></div>)}</div></section>)}</div>,device,page,preview)}
 <p className="pb-preview-note">Drag from handles only. Use Structure → Settings for precise movement, sizing and hidden elements. Escape cancels dragging. Scroll from content or margins.</p></div></div></div>;
}
function MediaControls({config,change,context,reset,selectable}:{config:MediaConfig;change:(v:Record<string,unknown>)=>void;context:RenderContext;reset:()=>void;selectable:boolean}){
 const [assets,setAssets]=useState<MediaAsset[]>([]),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[error,setError]=useState('');const c=mediaFor(config,context.device),selected=assets.find(a=>a.id===c.asset);
 useEffect(()=>{let active=true;context.media.list(query,category).then(a=>{if(active)setAssets(a);}).catch(()=>setError('Media library unavailable.'));return()=>{active=false;};},[context.media,query,category]);
 function responsive(values:Record<string,unknown>){change({... (context.device==='desktop'?values:{[context.device]:{...config[context.device],...values}}),...(typeof values.asset==='string'?{alt:''}:{})});}
 return <><h3>Media library</h3>{!selectable&&<p>Select an image-backed widget in Structure to replace its image.</p>}<label>Search media<input aria-label="Search media" value={query} onChange={e=>setQuery(e.target.value)}/></label>{context.media.categories&&<label>Category<select aria-label="Media category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All</option>{context.media.categories.map(x=><option key={x}>{x}</option>)}</select></label>}{error&&<p role="alert">{error}</p>}<div className="pb-picker-grid">{assets.map(a=><button type="button" key={a.id} disabled={!selectable||a.rights_status!=='APPROVED'||!context.media.validateSource(a)} onClick={()=>responsive({asset:a.id})} aria-pressed={c.asset===a.id}>{a.type==='image'&&context.media.validateSource(a)&&/* eslint-disable-next-line @next/next/no-img-element */<img src={a.source} alt=""/>}<small>{a.filename}</small><small>{a.rights_status==='NEEDS_RIGHTS_REVIEW'?'Needs rights review — selection unavailable':a.rights_status||'Rights unknown'}</small><small>{a.width||'?'} × {a.height||'?'} · {a.mime_type}</small><small>{a.provenance||'Provenance not supplied'}</small><small>Source: {a.source}</small></button>)}</div>
 {selected&&<><p className="pb-picker-meta">{selected.width||'?'} × {selected.height||'?'} · {selected.mime_type}<br/>{selected.provenance||'Provenance not supplied'}<br/>{selected.attribution}</p>{selected.rights_status!=='APPROVED'&&<p className="pb-warning">{selected.rights_status==='NEEDS_RIGHTS_REVIEW'?'Needs rights review':'Rights unknown'} — publication requires approved media.</p>}{selected.type==='image'&&<button type="button" className="pb-focal" aria-label="Set focal point on image" onClick={e=>{if(e.detail===0){e.currentTarget.closest('aside')?.querySelector<HTMLInputElement>('input[aria-label="Focal x"]')?.focus();return;}const r=e.currentTarget.getBoundingClientRect();responsive({x:Math.round((e.clientX-r.left)/r.width*100),y:Math.round((e.clientY-r.top)/r.height*100)});}}>{/* eslint-disable-next-line @next/next/no-img-element */}<img src={selected.source} alt={selected.alt||'Selected image focal point'}/><span style={{left:`${c.x}%`,top:`${c.y}%`}}/></button>}</>}
 {selectable&&<><p className="pb-preview-note">Asset and focal point apply to {context.device}. Fit, alt text, overlay and video options are shared.</p><button type="button" onClick={()=>responsive({asset:null})}>Remove image</button><button type="button" onClick={reset}>Reset media to default</button>{context.device!=='desktop'&&<button type="button" onClick={()=>change({[context.device]:{}})}>Use default image / crop</button>}
 <label>Alt text<input aria-label="Alt text" maxLength={500} value={config.alt} onChange={e=>change({alt:e.target.value})}/></label><label>Decorative<select aria-label="Decorative" value={String(config.decorative)} onChange={e=>change({decorative:e.target.value==='true'})}><option value="false">Meaningful image</option><option value="true">Decorative image</option></select></label>{(['x','y'] as const).map(k=><label key={k}>Focal {k}<input aria-label={`Focal ${k}`} type="range" min="0" max="100" value={c[k]} onChange={e=>responsive({[k]:Number(e.target.value)})}/><output>{c[k]}%</output></label>)}{(['fit','ratio','radius','overlay'] as const).map(k=><label key={k}>{k}<select aria-label={k} value={config[k]} onChange={e=>change({[k]:e.target.value})}>{(k==='fit'?['cover','contain']:k==='ratio'?['wide','square','portrait','natural']:k==='radius'?['none','small','large']:['none','light','medium','dark']).map(x=><option key={x}>{x}</option>)}</select></label>)}
 {selected?.type==='video'&&<><p>Video controls remain available. Autoplay requires muted audio.</p><label>Muted<select aria-label="Muted" value={String(config.muted)} onChange={e=>change({muted:e.target.value==='true',...(e.target.value==='false'?{autoplay:false}:{})})}><option value="true">Muted</option><option value="false">Sound on user playback</option></select></label><label>Controls<select aria-label="Controls" value="true" disabled><option value="true">Always available</option></select></label><label>Autoplay<select aria-label="Autoplay" value={String(config.autoplay)} onChange={e=>change({autoplay:e.target.value==='true',muted:true})}><option value="false">Off</option><option value="true">Muted autoplay</option></select></label><label>Loop<select value={String(config.loop)} onChange={e=>change({loop:e.target.value==='true'})}><option value="false">Off</option><option value="true">On</option></select></label><label>Poster<select value={config.poster||''} onChange={e=>change({poster:e.target.value||null})}><option value="">No poster</option>{assets.filter(a=>a.type==='image'&&a.rights_status==='APPROVED'&&context.media.validateSource(a)).map(a=><option key={a.id} value={a.id}>{a.filename}</option>)}</select></label></>}
 </>} </>;
}

function LinkField({label,value,save}:{label:string;value:string;save:(value:string)=>void}){const [input,setInput]=useState(value);useEffect(()=>setInput(value),[value]);return <input aria-label={label} value={input} onChange={e=>setInput(e.target.value)} onBlur={()=>save(input)}/>;}

function viewportY(e:PointerEvent<HTMLButtonElement>){const frame=e.currentTarget.ownerDocument.defaultView?.frameElement as HTMLIFrameElement|null;if(!frame)return e.clientY;const bounds=frame.getBoundingClientRect();return bounds.top+e.clientY*bounds.width/frame.clientWidth;}
