'use client';
import {useEffect,useState,useSyncExternalStore,type ReactNode,type CSSProperties} from 'react';
import {canRender,coreRegistry,effective,mediaFor,ordered,validatePage,type Definition,type Device,type ElementBase,type MediaAsset,type MediaConfig,type MediaProvider,type Page,type PermissionContext,type Widget} from './core';
export type RenderContext={device:Device;permissions:PermissionContext;data:Record<string,unknown>;media:MediaProvider};
export type RuntimeDefinition=Definition&{render:(config:Record<string,unknown>,context:RenderContext)=>ReactNode};
export type RuntimeRegistry=Record<string,RuntimeDefinition>;
const query='(max-width: 600px)',tablet='(max-width: 1100px)';
function subscribe(callback:()=>void){const m=matchMedia(query),t=matchMedia(tablet);m.addEventListener('change',callback);t.addEventListener('change',callback);return()=>{m.removeEventListener('change',callback);t.removeEventListener('change',callback);};}
export function useDevice():Device{return useSyncExternalStore(subscribe,()=>matchMedia(query).matches?'mobile':matchMedia(tablet).matches?'tablet':'desktop',()=> 'desktop');}
export function MediaView({config,context}:{config:MediaConfig;context:RenderContext}){
 const c=mediaFor(config,context.device);const reducedMotion=useSyncExternalStore(callback=>{const q=matchMedia('(prefers-reduced-motion: reduce)');q.addEventListener('change',callback);return()=>q.removeEventListener('change',callback);},()=>matchMedia('(prefers-reduced-motion: reduce)').matches,()=>true);const [asset,setAsset]=useState<MediaAsset|null>(null),[poster,setPoster]=useState<string|undefined>();
 useEffect(()=>{let active=true;setAsset(null);if(c.asset)context.media.get(c.asset).then(a=>{if(active&&a&&context.media.validateSource(a))setAsset(a);}).catch(()=>{});return()=>{active=false;};},[c.asset,context.media]);
 useEffect(()=>{let active=true;setPoster(undefined);if(c.poster)context.media.get(c.poster).then(a=>{if(active&&a?.type==='image'&&context.media.validateSource(a))setPoster(a.source);}).catch(()=>{});return()=>{active=false;};},[c.poster,context.media]);
 if(!asset)return <p className="pb-media-empty">{c.asset?'Image unavailable. Choose approved media in the editor.':'No image selected.'}</p>;
 const alt=c.decorative?'':c.alt||asset.alt;
 if(!c.decorative&&!alt)return <p className="pb-media-empty">This image needs meaningful alt text.</p>;
 const style:CSSProperties={objectFit:c.fit,objectPosition:`${c.x}% ${c.y}%`};
 return <figure className={`pb-media pb-ratio-${c.ratio} pb-radius-${c.radius}`}><div className="pb-media-frame">{asset.type==='video'?<video src={asset.source} poster={poster} muted={c.muted} autoPlay={c.autoplay&&c.muted&&!reducedMotion} loop={c.loop} controls playsInline aria-label={alt||'Decorative video'} style={style}/>:/* eslint-disable-next-line @next/next/no-img-element */<img src={asset.source} alt={alt} loading="lazy" style={style}/>}<span aria-hidden="true" className={`pb-overlay pb-overlay-${c.overlay}`}/></div>{(asset.rights_status==='NEEDS_RIGHTS_REVIEW'||asset.caption)&&<figcaption>{asset.rights_status==='NEEDS_RIGHTS_REVIEW'&&<span className="pb-warning">Needs rights review — not approved for publication. </span>}{asset.caption}</figcaption>}</figure>;
}
export function genericRuntime():RuntimeRegistry{return Object.fromEntries(Object.entries(coreRegistry).map(([type,definition])=>[type,{...definition,render:(c:Record<string,unknown>,ctx:RenderContext)=>{switch(type){case'heading':{const Tag=c.level as 'h2'|'h3'|'h4';return <Tag>{String(c.text)}</Tag>;}case'text':return <p className="pb-text">{String(c.text)}</p>;case'divider':return <hr/>;case'spacer':return <div aria-hidden="true" className={`pb-spacer pb-space-${c.size}`}/>;case'metric':return <dl className="pb-metric"><dt>{String(c.label)}</dt><dd>{String(c.value)}</dd></dl>;case'list':return <ul>{String(c.text).split('\n').filter(Boolean).map((line,i)=><li key={i}>{line}</li>)}</ul>;case'media':return <MediaView config={c as unknown as MediaConfig} context={ctx}/>;default:return null;}}}])) as RuntimeRegistry;}
export function elementProps(element:ElementBase,device:Device){const p=effective(element,device);return {className:`pb-element pb-space-${p.spacing} pb-align-${p.align} pb-density-${p.density} pb-surface-${p.surface} pb-border-${p.border} pb-container-${p.container}`,style:{gridColumn:`span ${p.width}`} as CSSProperties};}
export function WidgetView({widget,registry,context}:{widget:Widget;registry:RuntimeRegistry;context:RenderContext}){const def=registry[widget.type];if(!def||!def.devices.includes(context.device)||!canRender(def,context.permissions,context.data))return null;return <>{def.render(widget.config,context)}</>;}
export function PageRenderer({page,registry,context,fallback}:{page:Page;registry:RuntimeRegistry;context:RenderContext;fallback?:Page}){
 let valid:Page;try{valid=validatePage(page,registry);}catch{if(!fallback)return <p role="alert">Page layout unavailable.</p>;try{valid=validatePage(fallback,registry);}catch{return <p role="alert">Page layout unavailable.</p>;}}
 return <div className="pb-page">{ordered(valid.sections,context.device).filter(s=>effective(s,context.device).visible).map(s=><section key={s.id} {...elementProps(s,context.device)}><div className="pb-columns">{ordered(s.columns,context.device).filter(c=>effective(c,context.device).visible).map(c=><div key={c.id} {...elementProps(c,context.device)}><div className="pb-widgets">{ordered(c.widgets,context.device).filter(w=>effective(w,context.device).visible).map(w=><div key={w.id} {...elementProps(w,context.device)}><WidgetView widget={w} registry={registry} context={context}/></div>)}</div></div>)}</div></section>)}</div>;
}
