const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'../../..');
function compile(file,imports={}){const output={};const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;new Function('exports','require',code)(output,k=>imports[k]||require(k));return output;}
const core=compile('packages/page-builder/src/core.ts');
const links=compile('apps/web/lib/website/links.ts');
const registry=compile('apps/web/lib/website/registry.ts',{'@6ds/page-builder/core':core,'./links':links});
const defaults=compile('apps/web/lib/website/defaults.ts',{'@6ds/page-builder/core':core,'./registry':registry});
const {publicMediaProvider}=compile('apps/web/lib/website/media.ts');
for(const key of Object.keys(registry.pageTypes))test(key+' has a valid deterministic source fallback',()=>{const p=defaults.defaultLayout(key);assert.equal(p.page_id,'public-'+key);assert.deepEqual(defaults.resolvedLayout(null,key),p);assert.deepEqual(defaults.resolvedLayout({...p,schema_version:99},key),p);assert.deepEqual(defaults.defaultLayout(key),p);});
test('homepage preserves separate Arenal and coastal chapters',()=>{const types=defaults.defaultWidgets.home;assert.equal(types[1],'arenal-feature');assert.deepEqual(types.slice(2,5),['featured-experiences','benefits','trip-planning']);assert.equal(types[5],'pacific-coast');});
test('public widget compatibility and inventory authority',()=>{const page=defaults.defaultLayout('tours');const widget=page.sections[1].columns[0].widgets[0];for(const config of [{price:'1'},{supplier_id:1},{active:true},{availability:'available'},{limit:13},{css:'color:green'}]){widget.config=config;assert.throws(()=>core.validatePage(page,registry.publicRegistry('tours')));}widget.config={limit:4,surface:'ivory'};assert.doesNotThrow(()=>core.validatePage(page,registry.publicRegistry('tours')));widget.type='planning-form';assert.throws(()=>core.validatePage(page,registry.publicRegistry('tours')));});
test('tour context is required at runtime and cannot be persisted',()=>{const reg=registry.publicRegistry('tour-detail');assert.equal(core.canRender(reg['price-request'],{role:'public',permissions:[]},{}),false);assert.equal(core.canRender(reg['price-request'],{role:'public',permissions:[]},{tour:{slug:'demo'}}),true);assert.throws(()=>reg['price-request'].validate({tour:{retail_price:'1'}}));});
test('public media resolves stable catalog assets and refuses forged sources or rights',async()=>{const approved={id:'coast',source:'/images/coast/pacific-sunset-temporary.webp',filename:'Coast',alt:'Pacific sunset',rights_status:'APPROVED',type:'image'};const provider=publicMediaProvider([approved]);assert.equal(await provider.get('missing'),null);assert.equal((await provider.list('coast')).length,1);assert(provider.validateSource(approved));assert(!provider.validateSource({...approved,source:'https://untrusted.invalid/a.jpg'}));assert(!provider.validateSource({...approved,rights_status:'NEEDS_RIGHTS_REVIEW'}));});
test('customer runtime contains no editor imports',()=>{for(const file of ['public-canvas.tsx','website-page.tsx','public-media.tsx'])assert(!/from ['"][^'"]*\/editor['"]/.test(fs.readFileSync(path.join(root,'apps/web/components/website',file),'utf8')));});

test('public links allow supported schemes without credentials or executable content',()=>{for(const link of ['/tours/demo','#coast','https://example.com','mailto:info@volcanvacations.com','tel:+5065550100'])assert(links.safePublicLink(link));for(const link of ['javascript:alert(1)','data:text/html,test','//evil.invalid','https://user:secret@example.com','mailto:a@b.com?body=%0asecret'])assert(!links.safePublicLink(link));});
test('media-backed public widgets expose nested media without inventory override controls',()=>{for(const key of Object.keys(registry.pageTypes)){const reg=registry.publicRegistry(key);for(const type of registry.mediaWidgets)if(reg[type])assert.equal(reg[type].mediaKey,'media');for(const def of Object.values(reg))assert(!def.fields.some(f=>['price','supplier','availability_status'].includes(f.key)));}});
test('image-text orientation and full-width height use bounded presets',()=>{const reg=registry.publicRegistry('home');assert.doesNotThrow(()=>reg['image-text'].validate({layout:'image-right',href:'https://example.com'}));assert.throws(()=>reg['image-text'].validate({layout:'absolute',left:15}));assert.throws(()=>reg['full-width-media'].validate({height:'500px'}));});

test('public primary heroes are singular and generic headings cannot create extra H1s',()=>{for(const key of Object.keys(registry.pageTypes)){const reg=registry.publicRegistry(key),page=defaults.defaultLayout(key),hero=page.sections[0];page.sections.push({...structuredClone(hero),id:'duplicate-section',columns:[{...structuredClone(hero.columns[0]),id:'duplicate-column',widgets:[{...structuredClone(hero.columns[0].widgets[0]),id:'duplicate-widget'}]}]});assert.throws(()=>core.validatePage(page,reg));assert.throws(()=>reg.heading.validate({text:'Extra title',level:'h1'}));}});
test('approved media can be resolved during server rendering for crawlable alt text',()=>{const asset={id:'coast',source:'/images/coast/pacific-sunset-temporary.webp',alt:'Pacific sunset',rights_status:'APPROVED',type:'image'};const provider=publicMediaProvider([asset]);assert.deepEqual(provider.getSync('coast'),asset);assert.equal(provider.getSync('missing'),null);});
test('public editor exposes save/publish/revisions/restore only through scoped proxy',()=>{const editor=fs.readFileSync(path.join(root,'apps/web/components/website/editor/public-editor.tsx'),'utf8');for(const action of ['draft','publish','revisions','restore'])assert(editor.includes("call('"+action+"'"));assert(!editor.includes('Bearer '));assert(!editor.includes('/ops/'));const proxy=fs.readFileSync(path.join(root,'apps/web/lib/website/editor-proxy.ts'),'utf8');assert(proxy.includes('Same-origin JSON request required.'));assert(proxy.includes("cache:'no-store'"));});
test('publication and restore require confirmation and saved draft; errors have reload recovery',()=>{const editor=fs.readFileSync(path.join(root,'packages/page-builder/src/editor.tsx'),'utf8');assert(editor.includes('Publish the saved draft to the public website?'));assert(editor.includes("disabled={busy||dirty}"));assert(editor.includes('Restore this revision as a new public revision?'));assert(editor.includes('Reload latest saved layout'));assert(editor.includes("r.current?' · Current'"));});
test('renderer validation failure renders the source fallback instead of a broken page',()=>{const output={},React=require('react'),{renderToStaticMarkup}=require('react-dom/server');const code=ts.transpileModule(fs.readFileSync(path.join(root,'packages/page-builder/src/runtime.tsx'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText;new Function('exports','require',code)(output,k=>k==='./core'?core:require(k));const p={schema_version:1,page_id:'review',sections:[{...core.base('s'),columns:[{...core.base('c'),widgets:[{...core.base('w'),type:'heading',config:{text:'Source fallback',level:'h2'}}]}]}]};const html=renderToStaticMarkup(React.createElement(output.PageRenderer,{page:{schema_version:999},fallback:p,registry:output.genericRuntime(),context:{device:'desktop',permissions:{role:'public',permissions:[]},data:{},media:publicMediaProvider([])}}));assert(html.includes('<h2>Source fallback</h2>'));assert(!html.includes('Page layout unavailable'));});
