const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'../../..');
function compile(file,imports={}){const output={};const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;new Function('exports','require',code)(output,k=>imports[k]||require(k));return output;}
const core=compile('packages/page-builder/src/core.ts');
const registry=compile('apps/web/lib/website/registry.ts',{'@6ds/page-builder/core':core});
const defaults=compile('apps/web/lib/website/defaults.ts',{'@6ds/page-builder/core':core,'./registry':registry});
const {publicMediaProvider}=compile('apps/web/lib/website/media.ts');
for(const key of Object.keys(registry.pageTypes))test(key+' has a valid deterministic source fallback',()=>{const p=defaults.defaultLayout(key);assert.equal(p.page_id,'public-'+key);assert.deepEqual(defaults.resolvedLayout(null,key),p);assert.deepEqual(defaults.resolvedLayout({...p,schema_version:99},key),p);assert.deepEqual(defaults.defaultLayout(key),p);});
test('homepage preserves separate Arenal and coastal chapters',()=>{const types=defaults.defaultWidgets.home;assert.equal(types[1],'arenal-feature');assert.deepEqual(types.slice(2,5),['featured-experiences','benefits','trip-planning']);assert.equal(types[5],'pacific-coast');});
test('public widget compatibility and inventory authority',()=>{const page=defaults.defaultLayout('tours');const widget=page.sections[1].columns[0].widgets[0];for(const config of [{price:'1'},{supplier_id:1},{active:true},{availability:'available'},{limit:13},{css:'color:green'}]){widget.config=config;assert.throws(()=>core.validatePage(page,registry.publicRegistry('tours')));}widget.config={limit:4,surface:'ivory'};assert.doesNotThrow(()=>core.validatePage(page,registry.publicRegistry('tours')));widget.type='planning-form';assert.throws(()=>core.validatePage(page,registry.publicRegistry('tours')));});
test('tour context is required at runtime and cannot be persisted',()=>{const reg=registry.publicRegistry('tour-detail');assert.equal(core.canRender(reg['price-request'],{role:'public',permissions:[]},{}),false);assert.equal(core.canRender(reg['price-request'],{role:'public',permissions:[]},{tour:{slug:'demo'}}),true);assert.throws(()=>reg['price-request'].validate({tour:{retail_price:'1'}}));});
test('public media resolves stable catalog assets and refuses forged sources or rights',async()=>{const approved={id:'coast',source:'/images/coast/pacific-sunset-temporary.webp',filename:'Coast',alt:'Pacific sunset',rights_status:'APPROVED',type:'image'};const provider=publicMediaProvider([approved]);assert.equal(await provider.get('missing'),null);assert.equal((await provider.list('coast')).length,1);assert(provider.validateSource(approved));assert(!provider.validateSource({...approved,source:'https://untrusted.invalid/a.jpg'}));assert(!provider.validateSource({...approved,rights_status:'NEEDS_RIGHTS_REVIEW'}));});
test('customer runtime contains no editor imports',()=>{for(const file of ['public-canvas.tsx','website-page.tsx','public-media.tsx'])assert(!/from ['"][^'"]*\/editor['"]/.test(fs.readFileSync(path.join(root,'apps/web/components/website',file),'utf8')));});
