'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {useInventory,LoadState,Thumbnail} from './inventory-ui';
import {Modules,PageHeader,Table,label,When} from './ops-ui';
import {Booking,bookingStatuses} from '../lib/bookings';
import {Tour,Supplier} from '../lib/inventory';
import {Payment} from '../lib/payments';
import {InventoryContext} from '../lib/internal';
function useView(){const [view,setView]=useState('');useEffect(()=>setView(new URLSearchParams(window.location.search).get('view')||''),[]);return [view,setView] as const;}
const ready=(b:Booking)=>b.ready_for_payment&&!b.payment_received&&!['cancelled','completed'].includes(b.trip.status);
export function BookingsList(){const state=useInventory<Booking[]>('/ops/bookings');const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [supplier,setSupplier]=useState('');const [date,setDate]=useState('');const [view,setView]=useView();
 const all=state.data||[];const match=(b:Booking,v:string)=>v==='attention'?b.needs_attention:v==='new'?b.status==='new':v==='awaiting_supplier'?b.supplier_confirmation_status==='awaiting_supplier'&&!['cancelled','completed'].includes(b.status):v==='ready'?ready(b):v==='paid'?b.payment_received:v==='declined'?b.supplier_confirmation_status==='declined'&&!['cancelled','completed'].includes(b.status):true;
 const rows=all.filter(b=>match(b,view)&&(!status||(status==='attention'?b.needs_attention:b.status===status))&&(!supplier||String(b.supplier.id)===supplier)&&(!date||b.requested_date===date)&&`${b.reference} ${b.tour_name} ${(b.submitted_contact||b.customer).first_name} ${(b.submitted_contact||b.customer).last_name}`.toLowerCase().includes(search.toLowerCase()));
 return <><PageHeader title="Bookings" description="Customer requests and confirmations" icon="bookings"/>{state.data&&<Modules items={[['New','new'],['Awaiting Supplier','awaiting_supplier'],['Ready for Payment','ready'],['Paid','paid']].map(([name,key])=>({label:name,value:all.filter(b=>match(b,key)).length,onClick:()=>setView(key),active:view===key}))}/>}<div className="toolbar"><label className="search-field">Search bookings<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Reference, customer or experience…"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="attention">Needs Attention</option>{bookingStatuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Supplier<select value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">All suppliers</option>{Array.from(new Map(all.map(b=>[b.supplier.id,b.supplier.name])).entries()).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Requested date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button onClick={()=>{setSearch('');setStatus('');setSupplier('');setDate('');setView('');}}>Clear</button></div>{view&&<p className="muted">Showing {label(view)} bookings.</p>}{!state.data?<LoadState error={state.error} retry={state.retry}/>:<Table label="Bookings · USD reservation snapshots" headings={['Reference','Customer','Experience','Date','Status','Amount']} empty={!rows.length}>{rows.map(b=><tr key={b.id}><td><Link href={`/bookings/${b.id}`}>{b.reference}</Link><small>{b.quantity} travelers</small></td><td>{(b.submitted_contact||b.customer).first_name} {(b.submitted_contact||b.customer).last_name}</td><td>{b.tour_name}<small>{b.supplier.name}</small></td><td className="nowrap">{b.requested_date}</td><td><span className="ops-badge">{label(b.status)}</span><small>{b.payment_received?label(b.payment_status||'Paid'):ready(b)?'Ready for Payment':label(b.supplier_confirmation_status)}</small></td><td className="numeric">${b.retail_total}</td></tr>)}</Table>}</>;
}
export function ToursList(){const state=useInventory<Tour[]>('/ops/tours');const context=useInventory<InventoryContext>('/ops/directory/inventory');const [search,setSearch]=useState('');const [supplier,setSupplier]=useState('');const [destination,setDestination]=useState('');const [status,setStatus]=useState('');const all=state.data||[];const dest=(id:number)=>context.data?.product_destinations[id]||[];
 const match=(t:Tour,s:string)=>s==='active'?t.active:s==='featured'?t.featured:s==='review'?t.active&&(!t.primary_image||!t.short_description):s==='inactive'?!t.active:true;
 const rows=all.filter(t=>match(t,status)&&(!supplier||String(t.supplier_id)===supplier)&&(!destination||dest(t.id).some(d=>String(d.id)===destination))&&t.name.toLowerCase().includes(search.toLowerCase()));
 return <><PageHeader title="Tours" description="Experiences available through Volcan Vacations" icon="tours"><Link className="ops-button" href="/tours/new">New tour</Link></PageHeader>{state.data&&<Modules items={[['Active','active'],['Featured','featured'],['Needs Review','review'],['Inactive','inactive']].map(([name,key])=>({label:name,value:all.filter(t=>match(t,key)).length,onClick:()=>setStatus(key),active:status===key}))}/>}<div className="toolbar"><label className="search-field">Search tours<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tours…"/></label><label>Destination<select value={destination} onChange={e=>setDestination(e.target.value)}><option value="">All destinations</option>{context.data?.destinations.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Supplier<select value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">All suppliers</option>{Array.from(new Map(all.map(t=>[t.supplier_id,t.supplier.name])).entries()).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['active','featured','review','inactive'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><button onClick={()=>{setSearch('');setSupplier('');setDestination('');setStatus('');}}>Clear</button></div>{context.error&&<LoadState error={context.error} retry={context.retry}/>}<p className="muted">Needs Review: active tours missing a primary image or summary.</p>{!state.data?<LoadState error={state.error} retry={state.retry}/>:<Table label="Tour inventory · USD · internal pricing" headings={['Tour','Destination','Supplier','Retail','Cost','Margin','Status']} empty={!rows.length}>{rows.map(t=><tr key={t.id}><td><div className="tour-cell"><Thumbnail image={t.primary_image}/><Link href={`/tours/${t.id}`}>{t.name}</Link></div></td><td>{dest(t.id).map(d=>d.name).join(', ')||t.location||'Unmapped'}</td><td>{t.supplier.name}</td><td className="numeric">${t.retail_price}</td><td className="numeric">${t.supplier_cost}</td><td className="numeric">${t.gross_margin}</td><td className="status-cell">{t.active?'Active':'Inactive'}{t.featured&&<small>Featured</small>}</td></tr>)}</Table>}</>;
}
export function SuppliersList(){const state=useInventory<Supplier[]>('/ops/suppliers');const context=useInventory<InventoryContext>('/ops/directory/inventory');const [search,setSearch]=useState('');const [relationship,setRelationship]=useState('');const [service,setService]=useState('');const [destination,setDestination]=useState('');const all=state.data||[];const extra=(s:Supplier)=>context.data?.suppliers.find(x=>x.id===s.id);const followup=(s:Supplier)=>s.active&&['contacted','rates_requested'].includes(extra(s)?.relationship_status||'');
 const rows=all.filter(s=>`${s.name} ${s.contact_name||''}`.toLowerCase().includes(search.toLowerCase())&&(!relationship||(relationship==='followup'?followup(s):extra(s)?.relationship_status===relationship))&&(!service||extra(s)?.services.includes(service))&&(!destination||extra(s)?.destinations.some(d=>String(d.id)===destination)));
 return <><PageHeader title="Suppliers" description="Vendors and commercial relationships" icon="suppliers"><Link className="ops-button" href="/suppliers/new">New supplier</Link></PageHeader>{state.data&&context.data&&<Modules items={[['Prospects','prospect'],['Rates Requested','rates_requested'],['Contracted','contracted'],['Needs Follow-up','followup']].map(([name,key])=>({label:name,value:all.filter(s=>key==='followup'?followup(s):extra(s)?.relationship_status===key).length,onClick:()=>setRelationship(key),active:relationship===key}))}/>}<div className="toolbar"><label className="search-field">Search suppliers<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Supplier or contact…"/></label><label>Service<select value={service} onChange={e=>setService(e.target.value)}><option value="">All services</option>{['tour','transportation','hotel'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Relationship<select value={relationship} onChange={e=>setRelationship(e.target.value)}><option value="">All relationships</option>{['prospect','contacted','rates_requested','rates_received','negotiating','contracted','active','inactive','declined','followup'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Destination<select value={destination} onChange={e=>setDestination(e.target.value)}><option value="">All destinations</option>{context.data?.destinations.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button onClick={()=>{setSearch('');setRelationship('');setService('');setDestination('');}}>Clear</button></div><p className="muted">Follow-up: active suppliers contacted or awaiting requested rates. Destinations come from linked inventory.</p>{!state.data||!context.data?<LoadState error={state.error||context.error} retry={()=>{state.retry();context.retry();}}/>:<Table label="Supplier directory" headings={['Supplier','Services','Relationship','Contact','Agreements','Status']} empty={!rows.length}>{rows.map(s=><tr key={s.id}><td><Link href={`/suppliers/${s.id}`}>{s.name}</Link></td><td>{extra(s)?.services.map(label).join(', ')||'Not classified'}</td><td>{label(extra(s)?.relationship_status||'prospect')}</td><td>{s.contact_name||'—'}<small>{s.email||s.phone}</small></td><td><Link href={`/agreements?supplier=${s.id}`}>{extra(s)?.agreement_count||0} agreements</Link></td><td className="status-cell">{s.active?'Active':'Inactive'}</td></tr>)}</Table>}</>;
}
export function PaymentsList(){const [record,setRecord]=useState('');useEffect(()=>setRecord(new URLSearchParams(window.location.search).get('record')||''),[]);const state=useInventory<Payment[]>('/ops/payments');const bookings=useInventory<Booking[]>('/ops/bookings');const [search,setSearch]=useState('');const [date,setDate]=useState('');const [view,setView]=useView();const all=state.data||[];const match=(p:Payment,v:string)=>v==='pending'?['pending','created','approved'].includes(p.status):v==='paid'?p.status==='captured':v==='exceptions'?p.status==='failed'||p.reconciliation_required:v==='refunded'?['refunded','partially_refunded'].includes(p.status):true;
 const readyBookings=(bookings.data||[]).filter(ready);const rows=all.filter(p=>(!record||String(p.id)===record)&&match(p,view)&&(!date||p.created_at.slice(0,10)===date)&&`${p.booking_reference} ${p.customer} ${p.tour}`.toLowerCase().includes(search.toLowerCase()));const due=readyBookings.filter(b=>(!date||b.requested_date===date)&&`${b.reference} ${b.tour_name} ${b.customer.first_name} ${b.customer.last_name}`.toLowerCase().includes(search.toLowerCase()));
 return <><PageHeader title="Payments" description="Customer payment activity · PayPal Sandbox" icon="payments"/>{state.data&&bookings.data&&<Modules items={[{label:'Ready',value:readyBookings.length,onClick:()=>setView('ready'),active:view==='ready'},...['pending','paid','exceptions'].map(v=>({label:label(v),value:all.filter(p=>match(p,v)).length,onClick:()=>setView(v),active:view===v}))]}/>}<div className="toolbar"><label className="search-field">Search payments<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Booking, customer or tour…"/></label><label>Payment status<select value={view} onChange={e=>setView(e.target.value)}><option value="">All payment records</option>{['ready','pending','paid','exceptions','refunded'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>{view==='ready'?'Requested date':'Payment created date (UTC)'}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button onClick={()=>{setSearch('');setDate('');setView('');setRecord('');}}>Clear</button></div>{!state.data||!bookings.data?<LoadState error={state.error||bookings.error} retry={()=>{state.retry();bookings.retry();}}/>:view==='ready'?<Table label="Confirmed bookings awaiting payment" headings={['Booking','Customer','Amount','Status','Date']} empty={!due.length}>{due.map(b=><tr key={b.id}><td><Link href={`/bookings/${b.id}`}>{b.reference}</Link><small>{b.tour_name}</small></td><td>{b.customer.first_name} {b.customer.last_name}</td><td className="numeric">${b.retail_total} USD</td><td>Ready for Payment</td><td className="nowrap">{b.requested_date}</td></tr>)}</Table>:<Table label="Payments · captured funds only count as received" headings={['Booking','Customer','Amount','Provider','Status','Paid']} empty={!rows.length}>{rows.map(p=><tr key={p.id}><td><Link href={p.reservation_id?`/bookings/${p.reservation_id}`:'/payments'}>{p.booking_reference}</Link><small>{p.tour}</small></td><td>{p.customer}</td><td className="numeric">${p.amount} {p.currency}</td><td>{p.provider}<small>{p.provider_environment}</small></td><td><span className="ops-badge">{label(p.status)}</span>{(p.failure_code||p.reconciliation_required)&&<small className="ops-attention">{p.reconciliation_required?'Review required':p.failure_code}</small>}</td><td><When value={p.paid_at}/></td></tr>)}</Table>}</>;
}
