'use client';
import Link from 'next/link';
import {useInventory,LoadState} from './inventory-ui';
import {usePhone,PageHeader,Modules,NeedsAttention,Attention,useIdentity,label,When} from './ops-ui';
import {MyTasks} from './tasks';
import {Task} from '../lib/internal';
export type WorkBooking={id:number;reference:string;tour_name:string;requested_date:string;quantity:number;status:string;version:number;supplier_confirmation_status:string;availability_status:string;assigned_user_id:number|null;internal_notes:string|null;customer_notes:string|null;contact:{first_name:string;last_name:string;email:string;phone:string|null}|null;product_id:number};
type DashboardData={profile:string;my_tasks:Task[];task_counts:{my_open:number;due_today:number;overdue:number;waiting:number;shared:number};attention:Attention[];assigned_bookings:WorkBooking[];booking_counts?:{new:number;awaiting_supplier:number;ready:number;paid:number};vendor_counts?:Record<string,number>;inventory_counts?:{active:number;needs_review:number;suppliers:number;stale_availability:number};recent_payments?:{id:number;amount:string;currency:string;paid_at:string;reservation_id:number|null;status:string}[]};
export function Dashboard(){const phone=usePhone();const user=useIdentity();const state=useInventory<DashboardData>('/ops/dashboard');const owner=user.dashboard_profile==='Owner'&&user.permissions.includes('users.manage');const business=user.permissions.includes('bookings.read');const data=state.data;
 return <div className={owner?'dashboard-content owner-content':'dashboard-content execution-dashboard'}><PageHeader title={owner?'Business Overview':business&&user.dashboard_profile!=='Staff'?'Today in Operations':'My Workspace'} description={owner?'Bookings, vendor relationships and work requiring attention':business?'Daily booking execution and vendor follow-up':'Your assigned work and upcoming follow-up'} icon="dashboard"/>{!data?<LoadState error={state.error} retry={state.retry}/>:<>{phone&&!owner&&<><NeedsAttention items={data.attention}/><MyTasks tasks={data.my_tasks}/></>}{data.booking_counts&&user.dashboard_profile!=='Staff'?<Modules items={[{label:'New Booking Requests',icon:'work',tone:'blue',hint:'Awaiting review',value:data.booking_counts.new,href:'/bookings?view=new'},{label:'Awaiting Supplier',icon:'users',tone:'gold',hint:'Needs follow-up',value:data.booking_counts.awaiting_supplier,href:'/bookings?view=awaiting_supplier'},{label:'Ready for Payment',icon:'payments',tone:'positive',hint:'Customer action needed',value:data.booking_counts.ready,href:'/bookings?view=ready'},{label:'Paid Bookings',icon:'tasks',tone:'complete',hint:'Payment received',value:data.booking_counts.paid,href:'/bookings?view=paid'}]}/>:<Modules items={[{label:'My Open Tasks',value:data.task_counts.my_open,href:'/tasks?mine=true'},{label:'Due Today',value:data.task_counts.due_today,href:'/tasks?view=today'},{label:'Overdue',value:data.task_counts.overdue,href:'/tasks?overdue=true'},{label:'Waiting',value:data.task_counts.waiting,href:'/tasks?view=waiting'}]}/>}
 <div className={owner?'dashboard-grid owner-dashboard':'dashboard-grid'}><div>{(!phone||owner)&&<NeedsAttention items={data.attention}/>}{data.vendor_counts&&user.dashboard_profile!=='Staff'&&<section className="dashboard-section"><div className="section-heading"><h2>{owner?'Vendor Pipeline':'Vendor Work'}</h2><Link href="/suppliers">View suppliers →</Link></div><div className="vendor-pipeline">{Object.entries(data.vendor_counts).map(([key,count])=><div key={key}><strong>{count}</strong><span>{label(key)}</span></div>)}</div><small>Active suppliers · current relationship status</small></section>}{data.inventory_counts&&user.dashboard_profile!=='Staff'&&<section className="dashboard-section"><h2>{owner?'Inventory':'Availability & Inventory'}</h2><div className="vendor-pipeline"><div><strong>{data.inventory_counts.active}</strong><span>Active tours</span></div><div><strong>{data.inventory_counts.needs_review}</strong><span>Missing image or summary</span></div><div><strong>{data.inventory_counts.stale_availability}</strong><span>Upcoming checks stale</span></div></div><Link href="/availability">Review availability →</Link></section>}</div><div>{(!phone||owner)&&<MyTasks tasks={data.my_tasks}/>}{!business?<section className="dashboard-section"><div className="section-heading"><h2>My Bookings</h2><Link href="/work">View all →</Link></div>{data.assigned_bookings.length?<ul className="task-compact">{data.assigned_bookings.map(b=><li key={b.id}><Link href={`/work/${b.id}`}>{b.reference} · {b.tour_name}</Link><small>{b.requested_date} · {label(b.status)}</small></li>)}</ul>:<p>No active bookings assigned.</p>}</section>:owner?<section className="dashboard-section"><div className="section-heading"><h2>Recent Payments</h2><Link href="/payments">View payments →</Link></div>{data.recent_payments?.length?<ul className="task-compact">{data.recent_payments.map(p=><li key={p.id}><Link href={p.reservation_id?`/bookings/${p.reservation_id}`:'/payments'}>${p.amount} {p.currency} · {label(p.status)}</Link><small><When value={p.paid_at}/></small></li>)}</ul>:<p>No payments received.</p>}</section>:<section className="dashboard-section"><h2>Shared Work</h2><p>{data.task_counts.shared} open tasks await assignment.</p><Link href="/tasks?shared=true">Open task queue →</Link></section>}{owner&&<section className="vv-personality"><span>Pura vida</span><h2>Extraordinary Experiences</h2><p>Start with great operations.</p></section>}</div></div></>}</div>;
}
