'use client';
import {useState,FormEvent} from 'react';
import Link from 'next/link';
import {useInventory,LoadState} from './inventory-ui';
import {apiRequest} from '../lib/api';
import {label} from './ops-ui';
export function SupplierFoundation({id}:{id:string}){const state=useInventory<{relationship_status:string;service_types:string[]}>(`/ops/suppliers/${id}/foundation`);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [saved,setSaved]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setSaved(false);const f=new FormData(e.currentTarget);try{await apiRequest(`/ops/suppliers/${id}/foundation`,{method:'PUT',body:JSON.stringify({relationship_status:f.get('relationship'),service_types:f.getAll('services')})});setSaved(true);state.retry();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section id="supplier-relationship" className="ops-confirmation"><h2>Commercial relationship</h2>{!state.data?<LoadState error={state.error} retry={state.retry}/>:<form onSubmit={save} className="ops-editor"><fieldset disabled={busy}><label>Relationship status<select name="relationship" defaultValue={state.data.relationship_status}>{['prospect','contacted','rates_requested','rates_received','negotiating','contracted','active','inactive','declined'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><p>Supplier capabilities</p><div className="ops-actions">{['tour','transportation','hotel'].map(s=><label className="ops-check" key={s}><input type="checkbox" name="services" value={s} defaultChecked={state.data!.service_types.includes(s)}/>{label(s)}</label>)}</div><button>Save relationship</button></fieldset></form>}{error&&<p role="alert">{error}</p>}{saved&&<p role="status">Relationship saved.</p>}<Link href={`/agreements?supplier=${id}`}>View agreements and rates →</Link></section>;
}
export function TourDestinations({id}:{id:string}){const all=useInventory<{id:number;name:string;active:boolean}[]>('/ops/destinations');const current=useInventory<{id:number}[]>(`/ops/products/${id}/destinations`);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [saved,setSaved]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await apiRequest(`/ops/products/${id}/destinations`,{method:'PUT',body:JSON.stringify({destination_ids:f.getAll('destinations').map(Number)})});setSaved(true);current.retry();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="ops-confirmation"><h2>Destinations</h2>{!all.data||!current.data?<LoadState error={all.error||current.error} retry={()=>{all.retry();current.retry();}}/>:<form className="ops-editor" onSubmit={save}><fieldset disabled={busy}><div className="destination-options">{all.data.filter(d=>d.active||current.data!.some(c=>c.id===d.id)).map(d=><label key={d.id} className="ops-check"><input name="destinations" type="checkbox" value={d.id} defaultChecked={current.data!.some(c=>c.id===d.id)}/>{d.name}</label>)}</div><button>Save destinations</button></fieldset></form>}{error&&<p role="alert">{error}</p>}{saved&&<p role="status">Destinations saved.</p>}</section>;
}
