'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useState} from 'react';
import type {Identity} from '../lib/server-session';
import {IdentityContext,Icon,label} from './ops-ui';
import {Logout} from './auth-controls';
const primaryPaths=['/','/bookings','/work','/tours','/transportation','/suppliers','/availability','/tasks'];
const groups=[['','Dashboard','/','profile.read','dashboard'],['Work','Bookings','/bookings','bookings.read','bookings'],['Work','My bookings','/work','bookings.read_assigned','bookings'],['Work','Tasks','/tasks','tasks.read','tasks'],['Work','Customers','/customers','customers.read','users'],['Work','Trips','/trips','trips.read','work'],['Inventory','Tours','/tours','tours.read','tours'],['Inventory','Transportation','/transportation','transport.read','transportation'],['Inventory','Availability','/availability','availability.read','bookings'],['Vendors','Suppliers','/suppliers','suppliers.read','suppliers'],['Vendors','Agreements','/agreements','commercial.read','work'],['Finance','Payments','/payments','payments.read','payments'],['Admin','Users','/users','users.manage','users'],['Admin','Settings','/settings','settings.read','work']];
export function OpsShell({user,children}:{user:Identity;children:React.ReactNode}){
 const path=usePathname();const [open,setOpen]=useState(false);const visible=groups.filter(g=>user.permissions.includes(g[3]));const active=(href:string)=>href==='/'?path==='/':path.startsWith(href);const navLink=(g:string[])=><Link key={g[2]} href={g[2]} aria-current={active(g[2])?'page':undefined} onClick={()=>setOpen(false)}><Icon name={g[4]}/>{g[1]}</Link>;
 return <IdentityContext.Provider value={user}><a className="ops-skip" href="#ops-content">Skip to content</a><div className="ops-shell"><aside className={open?'sidebar open':'sidebar'}><Link href="/" className="brand" onClick={()=>setOpen(false)}><span className="vv-logo" role="img" aria-label="Volcan Vacations"/><span>OPERATIONS</span></Link><nav aria-label="Operations navigation">{visible.map((g,i)=><div key={g[2]}>{g[0]&&g[0]!==visible[i-1]?.[0]&&<p className="nav-group">{g[0]}</p>}<Link href={g[2]} onClick={()=>setOpen(false)} aria-current={(g[2]==='/'?path==='/':path.startsWith(g[2]))?'page':undefined}><Icon name={g[4]}/>{g[1]}</Link></div>)}</nav><p className="sidebar-note">Volcan Vacations<br/>Internal workspace</p></aside><div className="workspace"><header className="topbar"><Link className="top-brand" href="/" aria-label="Volcan Vacations Operations"><span className="vv-logo" role="img" aria-label="Volcan Vacations"/></Link><button className="menu-toggle" aria-expanded={open} aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>☰</button><span className="workspace-label">Operations <span>/ {visible.find(g=>g[2]==='/'?path==='/':path.startsWith(g[2]))?.[1]||'Workspace'}</span></span><nav className="desktop-navigation" aria-label="Primary Operations">{primaryPaths.flatMap(p=>visible.filter(g=>g[2]===p)).map(navLink)}{visible.some(g=>!primaryPaths.includes(g[2]))&&<details className="more-menu" onKeyDown={e=>{if(e.key==='Escape'){e.currentTarget.open=false;e.currentTarget.querySelector('summary')?.focus();}}}><summary className={visible.some(g=>!primaryPaths.includes(g[2])&&active(g[2]))?'selected':undefined}>More <span aria-hidden="true">⌄</span></summary><div>{visible.filter(g=>!primaryPaths.includes(g[2])).map(navLink)}</div></details>}</nav><details className="profile-menu" onKeyDown={e=>{if(e.key==='Escape'){e.currentTarget.open=false;e.currentTarget.querySelector('summary')?.focus();}}}><summary><span className="avatar">{user.display_name.slice(0,1)}</span><span>{user.display_name}<small>{label(user.role)}</small></span><span aria-hidden="true">⌄</span></summary><div><Link href="/">{user.dashboard_profile} dashboard</Link><Link href="/profile">Profile &amp; password</Link>{user.permissions.includes('settings.read')&&<Link href="/settings">Settings</Link>}<Logout/></div></details></header><main id="ops-content" className="ops-main">{children}</main></div></div></IdentityContext.Provider>;
}
