'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {PageHeader,Table,Modules,label,useIdentity} from './ops-ui';
import {useInventory,LoadState} from './inventory-ui';
type Customer={id:number;first_name:string;last_name:string;email:string;phone:string|null;preferred_contact_method:string|null;trip_ids:number[]};
type Trip={id:number;reference:string;customer_name:string;start_date:string|null;end_date:string|null;party_size:number;status:string;bookings:{id:number;tour:string;status:string}[]};
type Agreement={id:number;title:string;supplier_id:number;supplier_name:string;status:string;effective_from:string;effective_to:string|null;currency:string;rate_count:number;notes:string|null};
export function Customers(){const state=useInventory<Customer[]>('/ops/customers');const [search,setSearch]=useState('');const rows=(state.data||[]).filter(c=>`${c.first_name} ${c.last_name} ${c.email}`.toLowerCase().includes(search.toLowerCase()));return <><PageHeader title="Customers" description="Customer contacts and their linked trips" icon="users"/><div className="toolbar"><label className="search-field">Search customers<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{!state.data?<LoadState error={state.error} retry={state.retry}/>:<Table label="Customer directory · internal use" headings={['Customer','Contact','Preference','Trips']} empty={!rows.length}>{rows.map(c=><tr key={c.id}><td>{c.first_name} {c.last_name}</td><td>{c.email}<small>{c.phone}</small></td><td>{c.preferred_contact_method||'Not specified'}</td><td>{c.trip_ids.length?<Link href={`/trips?customer=${c.id}`}>{c.trip_ids.length} trips</Link>:'No trips'}</td></tr>)}</Table>}</>;}
export function Trips(){const state=useInventory<(Trip&{customer_id:number})[]>('/ops/trips');const [search,setSearch]=useState('');const [customer,setCustomer]=useState('');useEffect(()=>setCustomer(new URLSearchParams(window.location.search).get('customer')||''),[]);const rows=(state.data||[]).filter(t=>(!customer||String(t.customer_id)===customer)&&`${t.reference} ${t.customer_name}`.toLowerCase().includes(search.toLowerCase()));return <><PageHeader title="Trips" description="Customer travel plans and linked reservations" icon="bookings"/><div className="toolbar"><label className="search-field">Search trips<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><button onClick={()=>{setSearch('');setCustomer('');}}>Clear</button></div>{!state.data?<LoadState error={state.error} retry={state.retry}/>:<Table label="Trips · reservation confirmations remain separate" headings={['Reference','Customer','Travel dates','Party','Status','Bookings']} empty={!rows.length}>{rows.map(t=><tr key={t.id}><td>{t.reference}</td><td>{t.customer_name}</td><td>{t.start_date||'Not provided'}{t.end_date&&` → ${t.end_date}`}</td><td>{t.party_size}</td><td>{label(t.status)}</td><td>{t.bookings.map(b=><p key={b.id}><Link href={`/bookings/${b.id}`}>{b.tour}</Link><small>{label(b.status)}</small></p>)}</td></tr>)}</Table>}</>;}
export function Agreements(){const [record,setRecord]=useState('');const state=useInventory<Agreement[]>('/ops/agreements');const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [supplier,setSupplier]=useState('');useEffect(()=>{const q=new URLSearchParams(window.location.search);setRecord(q.get('record')||'');setStatus(q.get('status')||'');setSupplier(q.get('supplier')||'');},[]);const all=state.data||[];const rows=all.filter(a=>(!record||String(a.id)===record)&&(!status||a.status===status)&&(!supplier||String(a.supplier_id)===supplier)&&`${a.title} ${a.supplier_name}`.toLowerCase().includes(search.toLowerCase()));return <><PageHeader title="Agreements" description="Supplier agreements and dated commercial references" icon="work"/>{state.data&&<Modules items={['draft','in_review','approved','expired'].map(s=>({label:label(s),value:all.filter(a=>a.status===s).length,onClick:()=>setStatus(s),active:status===s}))}/>}<div className="toolbar"><label className="search-field">Search agreements<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['draft','in_review','approved','expired','terminated'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Supplier<select value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">All suppliers</option>{Array.from(new Map(all.map(a=>[a.supplier_id,a.supplier_name])).entries()).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><button onClick={()=>{setSearch('');setStatus('');setSupplier('');setRecord('');}}>Clear</button></div>{!state.data?<LoadState error={state.error} retry={state.retry}/>:<Table label="Commercial references · do not automatically change booking prices" headings={['Agreement','Supplier','Effective dates','Currency','Rates','Status']} empty={!rows.length}>{rows.map(a=><tr key={a.id}><td><details><summary>{a.title}</summary><p>{a.notes||'No notes.'}</p><AgreementRates id={a.id}/></details></td><td><Link href={`/suppliers/${a.supplier_id}`}>{a.supplier_name}</Link></td><td>{a.effective_from} → {a.effective_to||'Open ended'}</td><td>{a.currency}</td><td>{a.rate_count}</td><td>{label(a.status)}</td></tr>)}</Table>}</>;}
function AgreementRates({id}:{id:number}){const state=useInventory<{id:number;label:string;net_amount:string;retail_amount:string|null;unit_type:string}[]>(`/ops/agreements/${id}/rates`);return !state.data?<LoadState error={state.error} retry={state.retry}/>:state.data.length?<ul>{state.data.map(r=><li key={r.id}>{r.label} · Net {r.net_amount} · Retail {r.retail_amount||'Unspecified'} · {label(r.unit_type)}</li>)}</ul>:<p>No rates recorded.</p>;}
export function Profile({settings=false}:{settings?:boolean}){const user=useIdentity();return <><PageHeader title={settings?'Settings':'My Profile'} description={settings?'Workspace access and operational configuration':'Your internal Volcan Vacations account'} icon="users"/><section className="dashboard-section"><h2>{user.display_name}</h2><p>{user.email}</p><p>{label(user.role)} · {user.dashboard_profile} dashboard</p><Link className="ops-button" href="/change-password">Change password</Link></section>{settings&&<section className="dashboard-section"><h2>Workspace settings</h2><p>PayPal is Sandbox only. Live activation, customer accounts and automated communications remain deferred.</p><p>Session duration and trusted origins are managed through host configuration.</p><Link href="/users">Manage internal access →</Link></section>}</>;}
