'use client';
import {FilterPanel} from './ops-ui';
import {useFormFocus} from './ops-ui';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useState,useEffect,FormEvent} from 'react';
import {useInventory,LoadState} from './inventory-ui';
import {PageHeader,Modules,Table,When,useIdentity,label} from './ops-ui';
import {apiRequest} from '../lib/api';
import {Task,DirectoryUser,openTask,taskLink} from '../lib/internal';
const statuses=['open','in_progress','waiting','completed','cancelled'];const priorities=['low','normal','high','urgent'];
export function MyTasks({tasks}:{tasks:Task[]}){return <section className="dashboard-section"><div className="section-heading"><h2>My Tasks</h2><Link href="/tasks?mine=true">View all tasks →</Link></div>{tasks.length?<ul className="task-compact">{tasks.map(t=><li key={t.id}><Link href={`/tasks?task=${t.id}`}>{t.title}</Link><small>{label(t.priority)} · {label(t.status)} · {t.due_at?<When value={t.due_at}/>: 'No due date'}</small></li>)}</ul>:<p className="empty-state">You have no open tasks.<small className="task-empty-help">Tasks assigned to you will appear here.</small></p>}</section>;}
export function TasksPage(){const query=useSearchParams();const user=useIdentity();const [filters,setFilters]=useState({search:'',assigned:'',status:'',priority:'',view:''});const [editing,setEditing]=useState<Task|'new'|null>(null);const [saving,setSaving]=useState(false);const [actionError,setActionError]=useState('');
 async function quick(t:Task,status:string){setSaving(true);setActionError('');try{await apiRequest(`/ops/tasks/${t.id}`,{method:'PUT',body:JSON.stringify({title:t.title,description:t.description,assigned_user_id:t.assigned_user_id,priority:t.priority,status,queue_role:t.queue_role,due_at:t.due_at,related_entity_type:t.related_entity_type,related_entity_id:t.related_entity_id,expected_version:t.version})});state.retry();}catch(e){setActionError((e as Error).message);}finally{setSaving(false);}}
 const state=useInventory<Task[]>('/ops/tasks');const today=new Date().toISOString().slice(0,10);const now=Date.now();
 useEffect(()=>{setFilters(f=>({...f,assigned:query.has('shared')?'shared':'',view:query.has('mine')?'mine':query.has('overdue')?'overdue':query.get('view')||''}));},[query]);
 useEffect(()=>{const id=query.get('task');if(id&&state.data)setEditing(state.data.find(t=>t.id===Number(id))||null);},[query,state.data]);
 const all=state.data||[];const overdue=(t:Task)=>openTask(t)&&!!t.due_at&&new Date(t.due_at).getTime()<now;
 const due=(t:Task)=>openTask(t)&&t.due_at?.slice(0,10)===today;
 const records=all.filter(t=>(!filters.search||`${t.title} ${t.description||''}`.toLowerCase().includes(filters.search.toLowerCase()))&&(!filters.status||t.status===filters.status)&&(!filters.priority||t.priority===filters.priority)&&(!filters.assigned||(filters.assigned==='shared'?!t.assigned_user_id:String(t.assigned_user_id)===filters.assigned))&&(!filters.view||(filters.view==='mine'?t.assigned_user_id===user.id&&openTask(t):filters.view==='overdue'?overdue(t):filters.view==='today'?due(t):t.status==='waiting')));
 const filter=(key:keyof typeof filters,value:string)=>setFilters({...filters,[key]:value});
 return <><PageHeader title="Tasks" description="Work that needs attention" icon="tasks"><button disabled={saving} onClick={()=>setEditing('new')}>Create task</button></PageHeader>{state.data&&<Modules items={[['My Open',all.filter(t=>t.assigned_user_id===user.id&&openTask(t)).length,'mine'],['Due Today',all.filter(due).length,'today'],['Overdue',all.filter(overdue).length,'overdue'],['Waiting',all.filter(t=>t.status==='waiting').length,'waiting']].map(([name,count,view])=>({label:String(name),value:Number(count),onClick:()=>filter('view',String(view)),active:filters.view===view}))}/>}
 <FilterPanel><label className="search-field">Search tasks<input type="search" value={filters.search} onChange={e=>filter('search',e.target.value)} placeholder="Search tasks…"/></label><label>Assignee<select value={filters.assigned} onChange={e=>filter('assigned',e.target.value)}><option value="">All permitted work</option><option value={user.id}>Assigned to me</option>{user.permissions.includes('tasks.assign')&&<option value="shared">Shared queue</option>}{Array.from(new Map(all.filter(t=>t.assigned_user_id&&t.assigned_user_id!==user.id).map(t=>[t.assigned_user_id,t.assigned_name])).entries()).map(([id,name])=><option key={id} value={id!}>{name}</option>)}</select></label><label>Status<select value={filters.status} onChange={e=>filter('status',e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Priority<select value={filters.priority} onChange={e=>filter('priority',e.target.value)}><option value="">All priorities</option>{priorities.map(p=><option key={p} value={p}>{label(p)}</option>)}</select></label><button onClick={()=>setFilters({search:'',assigned:'',status:'',priority:'',view:''})}>Clear</button></FilterPanel>
 {actionError&&<p role="alert">{actionError} <button onClick={state.retry}>Reload tasks</button></p>}{editing&&<TaskEditor key={editing==='new'?'new':editing.id} task={editing==='new'?null:editing} onBusyChange={setSaving} done={()=>{setEditing(null);const url=new URL(window.location.href);url.searchParams.delete('task');window.history.replaceState(null,'',url.pathname+url.search);state.retry();}}/>}
 {!state.data?<LoadState error={state.error} retry={state.retry}/>:<Table responsive="rows" label="Tasks · due dates shown in your local time; day filters use UTC" headings={['Task','Related to','Assigned to','Priority','Due','Status','Actions']} empty={!records.length}>{records.map(t=>{const href=taskLink(t,!user.permissions.includes('bookings.read'));return <tr key={t.id}><td><button className="text-action" disabled={saving} onClick={()=>setEditing(t)}>{t.title}</button><small>{t.source==='system_generated'?'System task':'Manual task'}</small></td><td>{href?<Link href={href}>{label(t.related_entity_type!)} #{t.related_entity_id}</Link>:'—'}</td><td>{t.assigned_name||'Shared queue'}</td><td>{label(t.priority)}</td><td><When value={t.due_at}/>{overdue(t)&&<small className="ops-attention">Overdue</small>}</td><td><span className="ops-badge">{label(t.status)}</span></td><td><div className="task-quick-actions">{openTask(t)&&[['in_progress','Start'],['waiting','Wait'],['completed','Complete']].filter(([status])=>status!==t.status).map(([status,text])=><button key={status} disabled={saving} onClick={()=>quick(t,status)} aria-label={`${text}: ${t.title}`}>{text}</button>)}<button disabled={saving} onClick={()=>setEditing(t)} aria-label={`Edit notes: ${t.title}`}>Notes / edit</button></div></td></tr>;})}</Table>}</>;
}
function TaskEditor({task,done,onBusyChange}:{task:Task|null;done:()=>void;onBusyChange:(busy:boolean)=>void}){const formRef=useFormFocus();const user=useIdentity();const managers=user.permissions.includes('tasks.assign');const [people,setPeople]=useState<DirectoryUser[]>([]);const [assignee,setAssignee]=useState(String(task?.assigned_user_id??(task?'':user.id)));const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{if(managers)apiRequest<DirectoryUser[]>('/ops/directory').then(setPeople).catch(e=>setError(e.message));},[managers]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);onBusyChange(true);setError('');const f=new FormData(e.currentTarget);const value=(k:string)=>String(f.get(k)||'');
 const payload={title:value('title'),description:value('description')||null,assigned_user_id:managers?(assignee?Number(assignee):null):user.id,priority:value('priority'),status:value('status'),queue_role:value('queue_role')||'operations',due_at:value('due_at')?new Date(value('due_at')).toISOString():null,related_entity_type:value('related_entity_type')||null,related_entity_id:value('related_entity_id')?Number(value('related_entity_id')):null,...(task?{expected_version:task.version}:{})};
 try{await apiRequest(`/ops/tasks${task?`/${task.id}`:''}`,{method:task?'PUT':'POST',body:JSON.stringify(payload)});done();}catch(e){setError((e as Error).message);}finally{setBusy(false);onBusyChange(false);}}
 const local=(s:string)=>{const d=new Date(s);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
 return <form ref={formRef} className="ops-editor" onSubmit={save} key={task?.id||'new'}><fieldset disabled={busy}><legend>{task?'Edit task':'Create task'}</legend><label>Task title<input name="title" required maxLength={220} defaultValue={task?.title}/></label><label>Description<textarea name="description" rows={3} maxLength={10000} defaultValue={task?.description||''}/></label><div className="ops-fields">{managers?<label>Assign to<select name="assigned_user_id" aria-label="Assign to" value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Shared queue</option>{assignee&&!people.some(p=>String(p.id)===assignee)&&<option value={assignee}>{task?.assigned_name||user.display_name}</option>}{people.map(p=><option key={p.id} value={p.id}>{p.display_name} · {label(p.role)}</option>)}</select></label>:<input type="hidden" name="assigned_user_id" value={user.id}/>}<label>Priority<select name="priority" defaultValue={task?.priority||'normal'}>{priorities.map(p=><option key={p} value={p}>{label(p)}</option>)}</select></label><label>Task status<select name="status" aria-label="Task status" defaultValue={task?.status||'open'}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Due date (local time)<input type="datetime-local" name="due_at" defaultValue={task?.due_at?local(task.due_at):''}/></label>{user.permissions.includes('users.manage')&&<label>Work queue<select name="queue_role" defaultValue={task?.queue_role||'operations'}><option value="operations">Operations</option><option value="owner_admin">Owner only</option></select></label>}{managers||!task?<><label>Related record type<select name="related_entity_type" defaultValue={task?.related_entity_type||''}><option value="">None</option>{(managers?['booking','supplier','tour','payment','availability','agreement','customer','transport_route']:['booking','availability']).map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Related record ID<input name="related_entity_id" type="number" min="1" defaultValue={task?.related_entity_id||''}/></label></>:<><input type="hidden" name="related_entity_type" value={task.related_entity_type||''}/><input type="hidden" name="related_entity_id" value={task.related_entity_id||''}/></>}</div><div className="ops-actions"><button>{busy?'Saving…':'Save task'}</button><button type="button" onClick={done}>Close / reload</button></div></fieldset>{error&&<p role="alert">{error}</p>}{task&&<small>Created by {task.created_by_name||'System'}{task.completed_by_name&&` · Completed by ${task.completed_by_name}`}</small>}</form>;
}
export function RelatedTasks({bookingId}:{bookingId:number}){const state=useInventory<Task[]>(`/ops/tasks?related_entity_type=booking&related_entity_id=${bookingId}`);return <section className="ops-confirmation"><h2>Related Tasks</h2>{!state.data?<LoadState error={state.error} retry={state.retry}/>:state.data.length?<ul className="task-compact">{state.data.map(t=><li key={t.id}><Link href={`/tasks?task=${t.id}`}>{t.title}</Link><small>{t.assigned_name||'Shared queue'} · {label(t.status)}</small></li>)}</ul>:<p>No related tasks.</p>}<Link href="/tasks">Manage tasks →</Link></section>;}
