'use client';
import {FilterPanel} from './ops-ui';
import {useFormFocus} from './ops-ui';
import {useState,FormEvent} from 'react';
import {apiRequest} from '../lib/api';
import {InternalUser} from '../lib/internal';
import {PageHeader,Modules,Table,When,label} from './ops-ui';
import {useInventory,LoadState} from './inventory-ui';
export function UsersPage(){const state=useInventory<InternalUser[]>('/ops/users');const [editing,setEditing]=useState<InternalUser|'new'|null>(null);const [search,setSearch]=useState('');const [filter,setFilter]=useState('');const all=state.data||[];const rows=all.filter(u=>(!filter||(filter==='active'?u.active:u.role===filter))&&`${u.display_name} ${u.email}`.toLowerCase().includes(search.toLowerCase()));
 return <><PageHeader title="Users" description="Internal Volcan Vacations access" icon="users"><button onClick={()=>setEditing('new')}>Create user</button></PageHeader>{state.data&&<Modules items={[['Active','active'],['Owners','owner_admin'],['Operations','operations_partner'],['Staff','staff']].map(([name,key])=>({label:name,value:all.filter(u=>key==='active'?u.active:u.role===key).length,onClick:()=>setFilter(key),active:filter===key}))}/>}<FilterPanel><label className="search-field">Search users<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or email…"/></label><label>Role / status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All users</option>{['active','owner_admin','operations_partner','staff'].map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label><button onClick={()=>{setFilter('');setSearch('');}}>Clear</button></FilterPanel>{editing&&<UserEditor key={editing==='new'?'new':editing.id} user={editing==='new'?null:editing} done={()=>{setEditing(null);state.retry();}}/>}{!state.data?<LoadState error={state.error} retry={state.retry}/>:<Table label="Internal users · roles control access, dashboard profiles control emphasis" headings={['User','Role','Dashboard','Last Login','Status']} empty={!rows.length}>{rows.map(u=><tr key={u.id}><td><button className="text-action" onClick={()=>setEditing(u)}>{u.display_name}</button><small>{u.email}</small></td><td>{label(u.role)}</td><td>{u.dashboard_profile}</td><td><When value={u.last_login_at}/></td><td className="status-cell">{u.active?'Active':'Inactive'}{u.must_change_password&&<small>Temporary password</small>}</td></tr>)}</Table>}</>;
}
function UserEditor({user,done}:{user:InternalUser|null;done:()=>void}){const formRef=useFormFocus();const [role,setRole]=useState(user?.role||'staff');const [profile,setProfile]=useState(user?.dashboard_profile||'Staff');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setBusy(true);const f=new FormData(event.currentTarget);const data={display_name:f.get('display_name'),role:f.get('role'),dashboard_profile:f.get('dashboard_profile'),...(user?{active:f.has('active')}:{email:f.get('email'),password:f.get('password')})};try{await apiRequest(`/ops/users${user?`/${user.id}`:''}`,{method:user?'PUT':'POST',body:JSON.stringify(data)});done();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form ref={formRef} className="ops-editor" onSubmit={save}><fieldset disabled={busy}><legend>{user?'Manage user':'Create user'}</legend><div className="ops-fields"><label>Display name<input name="display_name" required maxLength={140} defaultValue={user?.display_name}/></label>{!user&&<label>Email<input name="email" type="email" required maxLength={180} autoComplete="off"/></label>}<label>Security role<select name="role" aria-label="Security role" value={role} onChange={e=>{setRole(e.target.value);setProfile(e.target.value==='owner_admin'?'Owner':e.target.value==='operations_partner'?'Operations':'Staff');}}>{['owner_admin','operations_partner','staff'].map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label><label>Dashboard profile<select name="dashboard_profile" aria-label="Dashboard profile" value={profile} onChange={e=>setProfile(e.target.value)}>{['Owner','Operations','Staff'].map(p=><option key={p}>{p}</option>)}</select></label>{!user&&<label>Temporary password<input name="password" type="password" autoComplete="new-password" minLength={15} maxLength={128} required/><small>Share securely. The user must change this password after signing in.</small></label>}</div>{user&&<label className="ops-check"><input name="active" type="checkbox" defaultChecked={user.active}/>Active account</label>}<p className="muted">Role and account changes sign this user out. The last active owner cannot be deactivated or demoted.</p><div className="ops-actions"><button>{busy?'Saving…':'Save user'}</button><button type="button" onClick={done}>Close</button></div></fieldset>{error&&<p role="alert">{error}</p>}</form>;
}
