'use client';
import {useState} from 'react';
import {apiRequest} from '../lib/api';
import {useInventory,LoadState} from './inventory-ui';
import {PageHeader,When} from './ops-ui';
type PageRow={key:string;title:string;path:string;published_status:string;draft_status:string;last_published:string|null;published_by:string|null;public_url:string};
export function WebsitePages(){const state=useInventory<PageRow[]>('/ops/website/pages');const [busy,setBusy]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<{title:string;rows:{id:number;number:number;created_at:string;actor_name:string;action:string;current:boolean}[]}|null>(null);
 async function edit(key:string){setBusy(true);setError('');try{const {url}=await apiRequest<{url:string}>(`/ops/website/pages/${key}/edit-session`,{method:'POST',body:'{}'});window.location.assign(url);}catch(e){setError((e as Error).message);setBusy(false);}}
 return <><PageHeader title="Website Pages" description="Manage the public Volcan Vacations website" icon="work"/><p>Open Edit to arrange public sections, text and media. Save Draft keeps changes private; the public site stays on its published or source layout.</p>{error&&<p role="alert">{error}</p>}{!state.data?<LoadState error={state.error} retry={state.retry}/>:<div className="website-page-list">{state.data.map(p=><section className="ops-confirmation" key={p.key}><h2>{p.title}</h2><p>{p.path}</p><dl><dt>Published</dt><dd>{p.published_status}</dd><dt>Draft</dt><dd>{p.draft_status}</dd><dt>Last published</dt><dd><When value={p.last_published}/></dd><dt>Published by</dt><dd>{p.published_by||'—'}</dd></dl><div className="ops-actions"><button disabled={busy} onClick={()=>edit(p.key)}>Edit {p.title}</button><a href={p.public_url} target="_blank" rel="noopener noreferrer">Preview {p.title}</a><button onClick={async()=>{try{setHistory({title:p.title,rows:await apiRequest(`/ops/website/pages/${p.key}/revisions`)});}catch(e){setError((e as Error).message);}}}>Revisions: {p.title}</button></div></section>)}</div>}{history&&<section className="ops-confirmation" aria-label="Website revision history"><h2>{history.title} revisions</h2>{history.rows.length?<ul>{history.rows.map(r=><li key={r.id}>Revision {r.number} · {r.actor_name} · {r.action}{r.current?' · Current':''} · <When value={r.created_at}/></li>)}</ul>:<p>No published revisions. The source default is active.</p>}<button onClick={()=>setHistory(null)}>Close revisions</button><p>Open Edit to preview and restore a revision as a new publication.</p></section>}</>;
}
type Asset={id:string;source:string;filename:string;width:number|null;height:number|null;alt:string;rights_status:string;provenance:string;mime_type:string};
export function WebsiteMedia(){const state=useInventory<Asset[]>('/ops/website/media');const [query,setQuery]=useState('');return <><PageHeader title="Website Media" description="Public media references and rights metadata" icon="tours"/><p>Review the catalog here. To select or replace an image, open a public page editor and choose Media. Bulk ingestion and storage are not enabled.</p><label>Search media<input value={query} onChange={e=>setQuery(e.target.value)}/></label>{!state.data?<LoadState error={state.error} retry={state.retry}/>:<div className="website-media-list">{state.data.filter(a=>(a.filename+' '+a.alt).toLowerCase().includes(query.toLowerCase())).map(a=><article className="ops-confirmation" key={a.id}><h2>{a.filename}</h2><p>{a.alt}</p><p>{a.width||'Unknown'} × {a.height||'unknown'} · {a.mime_type}</p><strong>{a.rights_status==='APPROVED'?'Approved':'Needs rights review'}</strong><p>{a.provenance}</p></article>)}</div>}</>;}
