'use client';
import Link from 'next/link';
import {useState,FormEvent} from 'react';
import {PageHeader,Table,label} from './ops-ui';
import {useInventory,LoadState} from './inventory-ui';
import {WorkBooking} from './dashboard';
import {RelatedTasks} from './tasks';
import {apiRequest} from '../lib/api';
export function WorkList(){const state=useInventory<WorkBooking[]>('/ops/work/bookings');const [search,setSearch]=useState('');const rows=(state.data||[]).filter(b=>`${b.reference} ${b.tour_name}`.toLowerCase().includes(search.toLowerCase()));return <><PageHeader title="My Bookings" description="Assigned requests, customer follow-up and availability work" icon="bookings"/><div className="toolbar"><label className="search-field">Search assigned bookings<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{!state.data?<LoadState error={state.error} retry={state.retry}/>:<Table label="Assigned and relevant bookings" headings={['Booking','Experience','Date','Party','Status']} empty={!rows.length}>{rows.map(b=><tr key={b.id}><td><Link href={`/work/${b.id}`}>{b.reference}</Link></td><td>{b.tour_name}</td><td>{b.requested_date}</td><td>{b.quantity}</td><td>{label(b.status)}<small>{label(b.supplier_confirmation_status)}</small></td></tr>)}</Table>}</>;}
export function WorkDetail({id}:{id:string}){const state=useInventory<WorkBooking>(`/ops/work/bookings/${id}`);return <><Link href="/work">← My bookings</Link><PageHeader title="Booking Follow-up" description="Customer contact and availability checks for your assigned work" icon="bookings"/>{!state.data?<LoadState error={state.error} retry={state.retry}/>:<WorkRecord key={state.data.version} booking={state.data} reload={state.retry}/>}</>;}
function WorkRecord({booking:b,reload}:{booking:WorkBooking;reload:()=>void}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState('');async function save(event:FormEvent<HTMLFormElement>,kind:string){event.preventDefault();setBusy(true);setError('');setSaved('');const f=new FormData(event.currentTarget);try{await apiRequest(`/ops/work/bookings/${b.id}/${kind}`,{method:kind==='followup'?'PUT':'POST',body:JSON.stringify(kind==='followup'?{internal_notes:f.get('notes'),expected_version:b.version}:{command_id:crypto.randomUUID(),event_type:'availability_checked',availability_status:f.get('status'),notes:f.get('notes')||null,expected_version:b.version})});setSaved('Saved.');reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="ops-booking-grid"><section><h2>{b.reference}</h2><p>{b.tour_name}</p><dl><dt>Date</dt><dd>{b.requested_date}</dd><dt>Party</dt><dd>{b.quantity}</dd><dt>Status</dt><dd>{label(b.status)}</dd><dt>Supplier</dt><dd>{label(b.supplier_confirmation_status)}</dd><dt>Request availability</dt><dd>{label(b.availability_status)}</dd></dl></section><section><h2>Customer contact</h2>{b.contact?<p>{b.contact.first_name} {b.contact.last_name}<br/>{b.contact.email}<br/>{b.contact.phone}</p>:<p>No submitted contact.</p>}<p>{b.customer_notes||'No customer notes.'}</p></section></div><form className="ops-editor" onSubmit={e=>save(e,'followup')}><fieldset disabled={busy}><legend>Customer follow-up</legend><label>Follow-up notes<textarea name="notes" defaultValue={b.internal_notes||''} maxLength={10000} rows={3}/></label><button>Save follow-up</button></fieldset></form><form className="ops-editor" onSubmit={e=>save(e,'availability')}><fieldset disabled={busy}><legend>Reservation availability check</legend><p className="muted">Records availability information for this request. Supplier confirmation is handled by Operations.</p><div className="ops-fields"><label>Checked availability<select name="status" aria-label="Checked availability" defaultValue={b.availability_status}>{['unknown','available','limited','unavailable','closed'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Check notes<textarea name="notes" rows={2} maxLength={10000}/></label></div><button>Record availability check</button></fieldset></form>{error&&<p role="alert">{error} <button onClick={reload}>Reload booking</button></p>}{saved&&<p role="status">{saved}</p>}<RelatedTasks bookingId={b.id}/></>;
}
