const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const root=path.resolve(__dirname,'../../..');
function compile(file,imports={}){const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText;const output={};new Function('exports','require',code)(output,key=>imports[key]||require(key));return output;}
const core=compile('packages/page-builder/src/core.ts'),runtime=compile('packages/page-builder/src/runtime.tsx',{'./core':core}),imports={'@6ds/page-builder/core':core,'@6ds/page-builder/runtime':runtime},vv=compile('apps/ops/lib/page-builder/registry.tsx',imports),defaults=compile('apps/ops/lib/page-builder/defaults.ts',imports);
const page=(type,widgets,registry)=>defaults.defaultPage(type,[[[12,widgets]]],registry);
test('every VV business widget has a valid default and rejects injected business data',()=>{for(const [type,widgets]of Object.entries(vv.pageWidgets)){const registry=vv.vvRegistry(type,{});assert.doesNotThrow(()=>core.validatePage(page(type,Object.keys(widgets),registry),registry,type));for(const key of Object.keys(widgets))assert.throws(()=>registry[key].validate({...registry[key].defaultConfig,customer_email:'private@example.invalid'}));}});
test('transportation published layout cannot mount rates/history for Staff',()=>{const registry=vv.vvRegistry('transportation-detail',{'route-summary':'VISIBLE ROUTE',rates:'PRIVATE RATE',history:'PRIVATE AUDIT'}),layout=page('transportation-detail',['route-summary','rates','history'],registry);const html=renderToStaticMarkup(React.createElement(runtime.PageRenderer,{page:layout,registry,context:{device:'mobile',permissions:{role:'staff',permissions:['transport.read']},data:{route_id:1},media:{}}}));assert(html.includes('VISIBLE ROUTE'));assert(!html.includes('PRIVATE'));});
test('missing live record context prevents business mounting',()=>{const registry=vv.vvRegistry('booking-detail',{'booking-summary':'PRIVATE BOOKING'});const html=renderToStaticMarkup(React.createElement(runtime.PageRenderer,{page:page('booking-detail',['booking-summary'],registry),registry,context:{device:'tablet',permissions:{role:'owner_admin',permissions:['bookings.read']},data:{},media:{}}}));assert(!html.includes('PRIVATE'));});
test('source defaults are deterministic and phone columns stack',()=>{const registry=vv.vvRegistry('owner-dashboard',{}),rows=[[[7,['needs-attention']],[5,['my-tasks']]]],one=defaults.defaultPage('owner-dashboard',rows,registry),two=defaults.defaultPage('owner-dashboard',rows,registry);assert.deepEqual(one,two);assert(one.sections[0].columns.every(c=>core.effective(c,'mobile').width===12));});
test('Partner phone default prioritizes execution without changing desktop order',()=>{const registry=vv.vvRegistry('operations-dashboard',{}),layout=defaults.defaultPage('operations-dashboard',[[[12,['new-bookings']]],[[12,['needs-attention','my-tasks']]]],registry);assert.equal(core.ordered(layout.sections,'mobile')[0].columns[0].widgets[0].type,'needs-attention');assert.equal(core.ordered(layout.sections,'desktop')[0].columns[0].widgets[0].type,'new-bookings');});
test('page-specific registry rejects foreign modules and duplicate financial forms',()=>{const registry=vv.vvRegistry('booking-detail',{}),layout=page('booking-detail',['payment'],registry);layout.sections[0].columns[0].widgets.push({...layout.sections[0].columns[0].widgets[0],id:'second-payment'});assert.throws(()=>core.validatePage(layout,registry));layout.sections[0].columns[0].widgets.pop();layout.sections[0].columns[0].widgets[0].type='vendor-services';assert.throws(()=>core.validatePage(layout,registry));});
