/* Local-only Operations 2.0 role, responsive and accessibility acceptance.
   Private test files contain random temporary users and test-owned fixture IDs. */
const {chromium}=require('playwright');const AxeBuilder=require('@axe-core/playwright').default;
const fs=require('fs');const assert=require('assert/strict');
const folder=process.env.VV_OPS2_REVIEW_DIR||'/tmp/vv-ops2-review';
(async()=>{
 assert.equal(process.env.VV_E2E_CONFIRM_DEMO,'yes');
 const users=JSON.parse(fs.readFileSync(folder+'/browser-users.json')).filter(u=>!process.env.VV_OPS2_ROLE||u.role===process.env.VV_OPS2_ROLE);const fixture=JSON.parse(fs.readFileSync(folder+'/fixtures.json'));
 const runId=Date.now();
 const browser=await chromium.launch({args:['--no-sandbox']});const results=[];const violations=[];const failures=[];
 try{for(const user of users){const context=await browser.newContext();await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname==='opulent-memory-p77vqgjpw7w6f64jr-3000.app.github.dev'&&url.pathname.startsWith('/images/')){const response=await route.fetch({url:'http://localhost:3000'+url.pathname+url.search});return route.fulfill({response});}if(url.hostname!=='localhost')return route.abort();return route.continue();});
 const page=await context.newPage();page.on('pageerror',e=>failures.push(e.message));await page.goto('http://localhost:3001/login');await page.getByLabel('Email',{exact:true}).fill(user.email);await page.getByLabel('Password',{exact:true}).fill(user.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('http://localhost:3001/');await page.waitForLoadState('networkidle');
 const role=user.role;const owner=role==='owner_admin';const staff=role==='staff';
 assert.equal(await page.getByRole('navigation').getByRole('link',{name:'Users',exact:true}).count(),owner?1:0);
 assert.equal(await page.getByRole('navigation').getByRole('link',{name:'Payments',exact:true}).count(),staff?0:1);
 assert.equal(await page.getByRole('heading',{level:1}).innerText(),owner?'Business Overview':staff?'My Workspace':'Today in Operations');
 const routes=staff?['/','/tasks','/work',`/work/${fixture.bookings[0].id}`]:['/','/bookings',`/bookings/${fixture.bookings[2].id}`,'/tasks','/suppliers',`/suppliers/${fixture.supplier.id}`,'/tours',`/tours/${fixture.tour.id}`,'/availability','/payments',...(owner?['/users','/customers','/trips','/agreements','/settings']:[])];
 for(const width of [1440,1024,768]){await page.setViewportSize({width,height:1000});for(const path of routes){await page.goto('http://localhost:3001'+path);await page.waitForLoadState('networkidle');await page.locator('h1').waitFor();
 const alerts=(await page.getByRole('alert').allTextContents()).filter(t=>t.trim());assert.deepEqual(alerts,[],role+' '+path+' unexpected error');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,role+' '+width+' '+path+' page overflow');
 assert.equal(await page.locator('h1').count(),1,role+' '+path+' heading count');
 const slug=path==='/'?'dashboard':path.replace(/^\//,'').replaceAll('/','-');await page.screenshot({path:`${folder}/${role}-${slug}-${width}.png`,fullPage:true});
 if(width===1440){const check=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();for(const v of check.violations)violations.push({role,path,id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))});}
 results.push({role,path,width,overflow:false});fs.writeFileSync(folder+'/role-review.json',JSON.stringify({results,violations,pageErrors:failures,providerCalls:0},null,2));}
 if(width===768){await page.getByRole('button',{name:'Toggle navigation'}).click();await page.getByRole('navigation').getByRole('link',{name:'Tasks',exact:true}).click();await page.waitForURL('**/tasks');assert.equal(await page.getByRole('button',{name:'Toggle navigation'}).getAttribute('aria-expanded'),'false');}}
 // Role-specific actions through the actual forms.
 await page.goto('http://localhost:3001/tasks');await page.waitForLoadState('networkidle');await page.getByRole('button',{name:'Create task',exact:true}).click();await page.getByLabel('Task title',{exact:true}).fill('DEMO '+role+' browser follow-up '+runId);await page.getByRole('button',{name:'Save task',exact:true}).click();await page.getByRole('button',{name:'DEMO '+role+' browser follow-up '+runId,exact:true}).waitFor();await page.getByRole('button',{name:'DEMO '+role+' browser follow-up '+runId,exact:true}).click();await page.getByLabel('Task status',{exact:true}).selectOption('in_progress');await Promise.all([page.waitForResponse(r=>r.url().includes('/api/ops/tasks/')&&r.request().method()==='PUT'&&r.status()===200),page.getByRole('button',{name:'Save task',exact:true}).click()]);await page.locator('.ops-editor').waitFor({state:'detached'});await page.getByRole('button',{name:'DEMO '+role+' browser follow-up '+runId,exact:true}).waitFor();
 await page.getByRole('button',{name:'DEMO '+role+' browser follow-up '+runId,exact:true}).click();await page.getByLabel('Task status',{exact:true}).selectOption('completed');await page.screenshot({path:`${folder}/${role}-task-editor-768.png`,fullPage:true});await Promise.all([page.waitForResponse(r=>r.url().includes('/api/ops/tasks/')&&r.request().method()==='PUT'&&r.status()===200),page.getByRole('button',{name:'Save task',exact:true}).click()]);await page.locator('.ops-editor').waitFor({state:'detached'});await page.getByRole('button',{name:'DEMO '+role+' browser follow-up '+runId,exact:true}).waitFor();
 if(staff){await page.goto(`http://localhost:3001/work/${fixture.bookings[0].id}`);await page.waitForLoadState('networkidle');await page.locator('textarea[name=notes]').first().fill('DEMO staff contacted customer about meeting point.');await Promise.all([page.waitForResponse(r=>r.url().endsWith('/followup')&&r.status()===200),page.getByRole('button',{name:'Save follow-up',exact:true}).click()]);await page.waitForLoadState('networkidle');await page.getByLabel('Checked availability',{exact:true}).selectOption('available');await Promise.all([page.waitForResponse(r=>r.url().endsWith('/availability')&&r.request().method()==='POST'&&r.status()===200),page.getByRole('button',{name:'Record availability check',exact:true}).click()]);await page.reload();await page.waitForLoadState('networkidle');const persisted=await (await context.request.get('http://localhost:3001/api/ops/work/bookings/'+fixture.bookings[0].id)).json();assert.equal(persisted.availability_status,'available');assert.match(persisted.internal_notes,/staff contacted/);assert.deepEqual((await page.getByRole('alert').allTextContents()).filter(t=>t.trim()),[]);}
 if(owner){await page.goto('http://localhost:3001/users');await page.waitForLoadState('networkidle');await page.getByRole('button',{name:'Create user',exact:true}).click();await page.getByLabel('Display name',{exact:true}).fill('DEMO access review '+runId);await page.locator('input[name=email]').fill('ops2-browser-'+runId+'@example.invalid');await page.locator('input[name=password]').fill(require('crypto').randomBytes(24).toString('base64url'));await page.getByLabel('Security role',{exact:true}).selectOption('staff');await page.getByLabel('Dashboard profile',{exact:true}).selectOption('Owner');await page.screenshot({path:`${folder}/owner-user-editor-768.png`,fullPage:true});await page.getByRole('button',{name:'Save user',exact:true}).click();await page.getByRole('button',{name:'DEMO access review '+runId,exact:true}).waitFor();await page.getByRole('button',{name:'DEMO access review '+runId,exact:true}).click();await page.getByLabel('Active account',{exact:true}).uncheck();await page.getByRole('button',{name:'Save user',exact:true}).click();await page.waitForLoadState('networkidle');assert.deepEqual((await page.getByRole('alert').allTextContents()).filter(t=>t.trim()),[]);}
 if(!owner){await page.goto('http://localhost:3001/users');await page.getByRole('heading',{name:'Access restricted',exact:true}).waitFor();assert.equal((await context.request.get('http://localhost:3001/api/ops/users')).status(),403);}
 await page.locator('.profile-menu summary').click();await page.getByRole('button',{name:'Logout',exact:true}).click();await page.waitForURL('**/login');assert.equal((await context.request.get('http://localhost:3001/api/ops/tasks')).status(),401);await page.screenshot({path:`${folder}/${role}-login-768.png`,fullPage:true});await context.close();
 }
 fs.writeFileSync(folder+'/role-review.json',JSON.stringify({results,violations,pageErrors:failures,providerCalls:0},null,2));console.log(JSON.stringify({responsiveChecks:results.length,roles:users.map(u=>u.role),axeViolations:violations.length,pageErrors:failures.length,providerCalls:0}));assert.deepEqual(failures,[]);assert.deepEqual(violations,[]);
 }finally{await browser.close();}
})().catch(e=>{console.error(e.message);process.exit(1)});
