"""Transportation reference inventory and typed task links; no booking changes."""
from alembic import op
import sqlalchemy as sa
revision = '0008_transportation_foundation'
down_revision = '0007_internal_users_tasks'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("node_type IN ('airport','city','destination','pickup_zone','hotel','other')", name='ck_transport_node_type'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('transport_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_node_id', sa.Integer(), nullable=False),
    sa.Column('destination_node_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('estimated_distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('estimated_distance_km IS NULL OR estimated_distance_km > 0', name='ck_transport_route_distance'),
    sa.CheckConstraint('estimated_duration_minutes IS NULL OR estimated_duration_minutes > 0', name='ck_transport_route_duration'),
    sa.CheckConstraint('origin_node_id != destination_node_id', name='ck_transport_distinct_nodes'),
    sa.ForeignKeyConstraint(['destination_node_id'], ['transport_nodes.id'], ),
    sa.ForeignKeyConstraint(['origin_node_id'], ['transport_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_node_id', 'destination_node_id', name='uq_transport_direction')
    )
    op.create_table('transport_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('booking_method', sa.String(length=100), nullable=False),
    sa.Column('pickup_notes', sa.Text(), nullable=True),
    sa.Column('dropoff_notes', sa.Text(), nullable=True),
    sa.Column('luggage_notes', sa.Text(), nullable=True),
    sa.Column('child_policy', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("service_type IN ('shared_shuttle','private_transfer','lake_crossing','other')", name='ck_transport_service_type'),
    sa.CheckConstraint('capacity IS NULL OR capacity > 0', name='ck_transport_capacity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['transport_routes.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id'),
    sa.UniqueConstraint('supplier_id', 'route_id', 'service_type', name='uq_transport_vendor_service')
    )
    op.create_table('transport_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_service_id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('rate_kind', sa.String(length=30), nullable=False),
    sa.Column('unit_basis', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vendor_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vv_retail', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('public_reference_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(rate_kind = 'vendor_rate' AND public_reference_price IS NULL AND (vendor_cost IS NOT NULL OR vv_retail IS NOT NULL)) OR (rate_kind = 'public_reference' AND vendor_cost IS NULL AND vv_retail IS NULL AND public_reference_price IS NOT NULL)", name='ck_transport_price_boundary'),
    sa.CheckConstraint("currency IN ('USD','CRC')", name='ck_transport_rate_currency'),
    sa.CheckConstraint("unit_basis IN ('per_person','per_vehicle')", name='ck_transport_rate_unit'),
    sa.CheckConstraint('(vendor_cost IS NULL OR vendor_cost >= 0) AND (vv_retail IS NULL OR vv_retail >= 0) AND (public_reference_price IS NULL OR public_reference_price >= 0)', name='ck_transport_positive_rates'),
    sa.CheckConstraint('effective_to >= effective_from', name='ck_transport_rate_dates'),
    sa.ForeignKeyConstraint(['agreement_id'], ['supplier_agreements.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['transport_rates.id'], ),
    sa.ForeignKeyConstraint(['vendor_service_id'], ['transport_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supersedes_id')
    )
    op.create_index(op.f('ix_transport_rates_vendor_service_id'), 'transport_rates', ['vendor_service_id'], unique=False)
    op.create_table('transport_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_service_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('days_mask', sa.Integer(), server_default='0', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('pickup_window_minutes', sa.Integer(), nullable=True),
    sa.Column('seasonal_notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('import_key', sa.String(length=200), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('days_mask BETWEEN 0 AND 127', name='ck_transport_weekdays'),
    sa.CheckConstraint('effective_from IS NULL OR effective_to IS NULL OR effective_to >= effective_from', name='ck_transport_schedule_dates'),
    sa.CheckConstraint('estimated_duration_minutes IS NULL OR estimated_duration_minutes > 0', name='ck_transport_schedule_duration'),
    sa.CheckConstraint('pickup_window_minutes IS NULL OR pickup_window_minutes >= 0', name='ck_transport_pickup_window'),
    sa.ForeignKeyConstraint(['vendor_service_id'], ['transport_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_key')
    )
    op.create_index(op.f('ix_transport_schedules_vendor_service_id'), 'transport_schedules', ['vendor_service_id'], unique=False)
    # ### end Alembic commands ###

    op.drop_constraint("ck_ops_task_related", "ops_tasks", type_="check")
    op.create_check_constraint("ck_ops_task_related", "ops_tasks", "(related_entity_type IS NULL AND related_entity_id IS NULL) OR (related_entity_type IN ('booking','supplier','tour','payment','availability','agreement','customer','transport_route') AND related_entity_id IS NOT NULL AND related_entity_id > 0)")

def downgrade():
    op.drop_constraint("ck_ops_task_related", "ops_tasks", type_="check")
    op.create_check_constraint("ck_ops_task_related", "ops_tasks", "(related_entity_type IS NULL AND related_entity_id IS NULL) OR (related_entity_type IN ('booking','supplier','tour','payment','availability','agreement','customer') AND related_entity_id IS NOT NULL AND related_entity_id > 0)")
    op.drop_table('transport_rates')
    op.drop_table('transport_schedules')
    op.drop_table('transport_services')
    op.drop_table('transport_routes')
    op.drop_table('transport_nodes')
