/* Run only against the isolated review stack documented in public-vv-acceptance.md. */
const {chromium}=require('playwright'),AxeBuilder=require('@axe-core/playwright').default,fs=require('fs'),assert=require('assert');
const dir=process.env.VV_REVIEW_DIR,web='http://localhost:13000',ops='http://localhost:13001';
assert(dir,'Set VV_REVIEW_DIR to the isolated review directory.');
const {password}=JSON.parse(fs.readFileSync(dir+'/credentials.json')),api=fs.readFileSync(dir+'/public-api-origin.txt','utf8').trim();
(async()=>{const browser=await chromium.launch({args:['--no-sandbox']}),errors=[],results=[];let context,page;
async function setup(role='owner_admin'){
 const c=await browser.newContext();await c.route(api+'/**',async r=>{assert(!/paypal/i.test(r.request().url()),'Provider transactions forbidden');const response=await r.fetch({url:r.request().url().replace(api,'http://localhost:18000')});await r.fulfill({status:response.status(),headers:response.headers(),body:await response.body()});});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto(ops+'/login');await p.getByLabel('Email',{exact:true}).fill(role+'@example.invalid');await p.getByLabel('Password',{exact:true}).fill(password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.waitForURL(ops+'/');return [c,p];}
async function edit(p){await p.goto(ops+'/website/pages');await p.getByRole('button',{name:'Edit Home',exact:true}).click();await p.waitForURL(web+'/website-editor/home');await p.locator('.pb-editor').waitFor();await p.frameLocator('iframe').locator('.home-hero h1').waitFor();}
async function save(p){const response=p.waitForResponse(r=>r.url().endsWith('/home/draft')&&r.request().method()==='PUT');await p.getByRole('button',{name:'Save Draft',exact:true}).click();assert.equal((await response).status(),200);await p.getByText('Draft saved. Published page unchanged.',{exact:true}).waitFor();}
async function publish(p){const response=p.waitForResponse(r=>r.url().endsWith('/home/publish'));await p.getByRole('button',{name:'Publish',exact:true}).click();assert.equal((await response).status(),200);await p.getByText('Page published.',{exact:true}).waitFor();}
async function heading(p,text){await p.getByRole('tab',{name:'Structure',exact:true}).click();await p.locator('.pb-tree > li').first().locator('ul ul button').first().click();await p.getByLabel('Headline',{exact:true}).fill(text);}
async function publicPage(c){const p=await c.newPage();await p.goto(web+'/');await p.locator('.home-hero h1').waitFor();return p;}
async function revisions(p){await p.getByRole('button',{name:'Revisions',exact:true}).click();await p.getByRole('heading',{name:'Published revisions',exact:true}).waitFor();}
try{
 [context,page]=await setup();await edit(page);await save(page);await publish(page); // Explicit baseline revision, isolated only.
 const original=await publicPage(context),originalHeading=await original.locator('h1').innerText();await original.close();
 for(const width of [1440,1024,768]){
  await page.setViewportSize({width,height:1000});await edit(page);
  await heading(page,'Review publication '+width);assert(await page.getByRole('button',{name:'Publish',exact:true}).isDisabled());
  await page.getByRole('button',{name:'Change Image',exact:true}).click();await page.getByLabel('Search media',{exact:true}).fill('papagayo-temporary');const tile=page.locator('.pb-picker-grid button').filter({hasText:'papagayo-temporary.webp'});assert((await tile.innerText()).includes('Source:'));await tile.click();await page.getByLabel('Alt text',{exact:true}).fill('Reviewed illustrative Pacific cove');await page.getByRole('button',{name:'Set focal point on image',exact:true}).click({position:{x:75,y:45}});await page.getByLabel('overlay',{exact:true}).selectOption('dark');
  await page.getByRole('button',{name:'Tablet',exact:true}).click();await page.getByLabel('Focal x',{exact:true}).fill('67');await page.getByRole('button',{name:'Mobile',exact:true}).click();await page.getByLabel('Focal y',{exact:true}).fill('31');await page.getByRole('button',{name:'Desktop',exact:true}).click();
  await page.getByRole('tab',{name:'Structure',exact:true}).click();await page.locator('.pb-tree > li > button').nth(3).click();await page.getByRole('button',{name:'Move Down',exact:true}).click();await save(page);
  const before=await publicPage(context);assert.equal(await before.locator('h1').innerText(),originalHeading);await before.close();
  await page.getByRole('button',{name:'Preview',exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);await publish(page);
  const live=await publicPage(context);assert.equal(await live.locator('h1').innerText(),'Review publication '+width);await live.locator('.home-hero img[src*="papagayo"]').waitFor();assert.equal(await live.locator('.pb-editor').count(),0);const html=await (await context.request.get(web+'/')).text();assert(html.includes('Reviewed illustrative Pacific cove'),'Published alt text must be server-rendered');await live.screenshot({path:dir+'/published-'+width+'.png',fullPage:true});await live.close();
  await revisions(page);assert(await page.locator('.pb-revisions').getByText(/Current/).count());await page.screenshot({path:dir+'/revisions-'+width+'.png'});
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.equal(axe.violations.length,0,JSON.stringify(axe.violations.map(v=>v.id)));
  const response=page.waitForResponse(r=>r.url().endsWith('/home/restore'));await page.getByRole('button',{name:'Restore revision 1',exact:true}).click();assert.equal((await response).status(),200);await page.getByText('Restored as a new published revision.',{exact:true}).waitFor();assert(await page.locator('.pb-revisions').getByText(/restored.*Current/).count());const restored=await publicPage(context);assert.equal(await restored.locator('h1').innerText(),originalHeading);await restored.close();results.push({width,publish:true,restoreAsNew:true,privateDraft:true,axe:0});
 }
 const [other,b]=await setup();await edit(page);await edit(b);await heading(b,'Session B publication');await save(b);await publish(b);const stale=page.waitForResponse(r=>r.url().endsWith('/home/publish'));await page.getByRole('button',{name:'Publish',exact:true}).click();assert.equal((await stale).status(),409);await page.getByRole('alert').filter({hasText:'another session'}).waitFor();await page.getByRole('button',{name:'Reload latest saved layout',exact:true}).click();await page.locator('.pb-editor').waitFor();await page.frameLocator('iframe').getByRole('heading',{name:'Session B publication',exact:true}).waitFor();await revisions(page);await page.getByRole('button',{name:'Restore revision 1',exact:true}).click();await page.getByText('Restored as a new published revision.',{exact:true}).waitFor();await other.close();results.push({stalePublication:409,reloadRecovery:true});
 // Rights warning from a deliberately saved review-only draft via the same private proxy.
 await page.getByRole('button',{name:'Export / Import',exact:true}).click();const layout=JSON.parse(await page.getByLabel('Complete layout JSON',{exact:true}).inputValue());const config={asset:'vv-arenal',alt:'Arenal',decorative:false,fit:'cover',x:50,y:50,ratio:'wide',radius:'small',overlay:'dark',tablet:{},mobile:{},autoplay:false,muted:true,loop:false,controls:true,poster:null};layout.sections[0].columns[0].widgets[0].config.media=config;
 await page.getByLabel('Import layout JSON',{exact:true}).fill(JSON.stringify(layout));await page.getByRole('button',{name:'Import into draft',exact:true}).click();await save(page);const blocked=page.waitForResponse(r=>r.url().endsWith('/home/publish'));await page.getByRole('button',{name:'Publish',exact:true}).click();assert.equal((await blocked).status(),422);await page.getByRole('alert').filter({hasText:'rights review'}).waitFor();await revisions(page);await page.getByRole('button',{name:'Restore revision 1',exact:true}).click();await page.getByText('Restored as a new published revision.',{exact:true}).waitFor();results.push({mediaRightsBlock:422});
 for(const role of ['operations_partner','staff']){const [c,p]=await setup(role);assert.equal((await c.request.get(ops+'/api/ops/website/pages')).status(),403);await p.goto(ops+'/website/pages');assert.equal(await p.getByRole('button',{name:'Edit Home',exact:true}).count(),0);for(const path of ['/','/bookings','/tasks']){await p.goto(ops+path);assert.equal(await p.locator('.pb-editor').count(),0);}await c.close();results.push({role,websiteDenied:true,operations:true});}
 const anonymous=await browser.newContext();for(const path of ['/api/website-editor/pages/home/revisions','/api/website-editor/pages/home/publish']){const r=path.endsWith('publish')?await anonymous.request.post(web+path,{data:{}}):await anonymous.request.get(web+path);assert.equal(r.status(),401);}await anonymous.close();assert.equal(errors.length,0,errors.join('\n'));console.log(JSON.stringify({results,errors}));
}catch(e){console.error(e.stack);if(page)await page.screenshot({path:dir+'/failure.png'});process.exitCode=1;}finally{fs.writeFileSync(dir+'/publication-results.json',JSON.stringify({results,errors},null,2));await browser.close();}})();
